### ISSUE TITLE
Charging enables motors on Alternate H1 motherboard ...

### ISSUE THREAD

**Issue by vamfun** [EFeru/hoverboard-firmware-hack-FOC#126]
I have the ROHS Gen 3 green board that has 5 GPIO 
Pins wired to different pins than the basic stm32 FOC board. THE pins are described in issue #162 of NiklasFauth hoverboard repository. Summarized changes are here:

![image](https://user-images.githubusercontent.com/4359767/104172604-64cace80-53b9-11eb-8e0d-ea4a6afe6821.jpeg)

I am using the VARIANT_ADC and all works fine except , plugging the charger in activates the board as if I pressed the power-on switch.  The board has a normal power on beep , the motors engage and respond to inputs.   I can disengage the board but the buzzer stays on with an annoying continuous tone.   I've tried unsuccessfully to trace the charging circuit.  It does seem that it doesn't match the FOC circuit for the parts that I've traced.   Print shows the charging pin stays low all the time with or without the charger plugged in....seems suspect to me since the pin has a pull-up and should read high with the charger unplugged.

I've found a workaround to eliminate the continuous tone by altering the poweroff() routine to include a beepCount(0,0,0) in the last while(1){} to reset buzzer.

Anyone have any thoughts re this circuit or is this normal for my board.

Board taken from Hover-1 H1 hoverboard.
![image](https://user-images.githubusercontent.com/4359767/104234442-43450380-5408-11eb-8ae6-5d65df9e976c.jpeg)

**Comment by Candas1** [comment]
Hi, do you have a picture of your mainboard you can share ?

PA1 is the ON/OFF button in the firmware. In the changes you share it seems to be used for DCLINK ?

**Comment by vamfun** [comment]
@Candas1 ...I added a picture to my original post.  
Thanks for the board spreadsheet.  How do you know all the boards are GD chips rather than STM32?

**Comment by Candas1** [comment]
OK your board looks quite common.
But you have 6 wires on hall sensor cables, one being white?

I just started with boards me and my friends own, and all had gd32 chips. But I think a stm32f103rct6 or a gd32f103rct6 would work the same.

So I have the feeling the pin mapping is still not correct in your case?

**Comment by vamfun** [comment]
Very observant, I didn’t notice the 6 wire halls.   Well, I’m not sure why you think my pins are not quite correct.   I have verified by tracing all but the charger pin  which alludes me still.    My chip has ST marking but still might be a  GD clone with ST markings.    



http://vamfun.wordpress.com
Robot musing blog
iPhone

**Comment by dnhkng** [comment]
@vamfun Did you solve this issue?  I'm also using a 6-wire sensor hoverboard controller board, and plugging in the charger turns the system on, and powers the wheels!
`#define BOARD_VARIANT           1 `

If I then turn the system off using the power button, the motors shut down, but the buzzer runs constantly! No way can I charge it like that!


 If I just leave the system on to charge, after a minute or two, there's a time-out, and the system tries to power down. But again, I get a constant loud beeping!

**Comment by Candas1** [comment]
Because your board has a problem.
It's described on the troubleshooting section of the wiki.

**Comment by dnhkng** [comment]
I made an edit to the code, to disable the beep. Do you think it's necessary to repair the board? The LEDs remain lit, so there is a current draw and the batteries will take longer to charge, but if that's the only issue, I can live with that for now.
