### ISSUE TITLE
Hovercar variant

### ISSUE THREAD

**Issue by genetgenet** [EFeru/hoverboard-firmware-hack-FOC#174]
Hi and thanx for this great project :)

I'm building an older kettcar with an hoverboard from 2014. It has the chip GD32F103RCT6. I unlocked the mcu but had a problem but after a while it worked somehow. I followed the hoverboard youtube clip and flashed the firmware with vscode, soldered the 3.3v wire for gas, connected thrustmaster pedals (pots) and tried it out. I have not soldered any pull down resistors "are they neseccary"? The motors spin up and then go slow no matter how much gas i give. I have tried to run on the floor but it just stutters forward on slow speed. I have tried to swap phase wires but both wheels only run at original wiring colors. Could the programming have gone wrong somehow? I'm lost here. I only have the st link no other debugging. I do have another older hoverboard with the stm32 chip but i would like to solve this first. When i swapped phase wires i have only swapped colors in one direction. I will post some pictures. Before the flash it worked like an ordinary hoverboard without problems.

**Comment by genetgenet** [comment]
Uploading VID_20210510_212406.mp4…

**Comment by EmanuelFeru** [comment]
The board you have might have slightly different pinouts. @Candas1 knows better. Have you tried with this macro set to 1?
https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/blob/0709e4cb62ef1d0bfedfc6bc3187614d5862acd6/Inc/config.h#L66

**Comment by Candas1** [comment]
Hi,

The [alternate wiring](https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/wiki/Firmware-Compatibility#pin-mapping) is for some boards with 6 wires on hall sensor cables.
Genetgenet, are you uploading a video ? it's not visible.
Have you tried the [autocalibration](https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/wiki/Input-Calibration) ?

**Comment by genetgenet** [comment]
![IMG_20210509_195027](https://user-images.githubusercontent.com/50130313/117722473-65496980-b1e1-11eb-8b74-334bbb276d0f.jpg)

**Comment by genetgenet** [comment]
Yes i have done autocalibration several times. The video did not upload for some reason. Here is the video link.

https://youtube.com/shorts/ClvuGA6BHeE?feature=share

**Comment by Candas1** [comment]
Have you picked the right variant? Changed anything in config.h file?

**Comment by genetgenet** [comment]
No i have not changed anything. I'm not familiar with vscode. I just followed instructions on the youtube hovercar video. Could something still gone wrong with the programming? As a said i had some problem unlocking the mcu, there were 3 boxes still checked that i could not uncheck as in the picture if it has something to do with this? (user configuration option byte) nrst_stop, nrst_stdby and wdg_sw.

**Comment by genetgenet** [comment]
![Screenshot_20210511_051809_com android chrome](https://user-images.githubusercontent.com/50130313/117753657-28996480-b219-11eb-9a8d-c08144c3d59b.jpg)

**Comment by genetgenet** [comment]
I can understand some level of programming but i have not started to look into it yet.

**Comment by Candas1** [comment]
No you don't need to uncheck those options it's ok.
If the firmware is in, the flashing went well.

Is anything happening when you press the brake pedal ? When you press it twice ?

**Comment by Candas1** [comment]
Ok this is the way to activate reverse, only works at zero speed.
Just wanted to confirm as this option is only available in Hovercar variant

**Comment by Candas1** [comment]
When wheels are not on the floor, braking can lead the wheels to oscillate forward/backwards, with a beep when going backwards, this is OK and will not happen on the floor.
But it still doesn't explain your problem.

Do you have a better picture of your mainboard without the cables in the middle ?

**Comment by genetgenet** [comment]
https://youtu.be/NlG4vDOBUjg

**Comment by genetgenet** [comment]
![IMG_20210508_221841](https://user-images.githubusercontent.com/50130313/117919451-4e903900-b2ed-11eb-93a7-c5d53c3e6df0.jpg)
Gas pedal

**Comment by genetgenet** [comment]
![IMG_20210508_221914](https://user-images.githubusercontent.com/50130313/117919485-5ea81880-b2ed-11eb-9e70-18662d350d8a.jpg)
Brake pedal has an additional wire on the bottom

**Comment by Candas1** [comment]
Your mainboard seems ok.
You need to check your wiring, you can use a multimeter

**Comment by genetgenet** [comment]
Check all wiring? Can you be more specific? Wiring to pedals

**Comment by genetgenet** [comment]
Hi again.

I connected 2 handlebar accelerator hall sensored but it did not work. Checked all cables found nothing wrong so i have redone the procedure from the beginning. First i used st32cubeprogrammer shown in another video to try unlocking mcu (even thou it should be unlocked) and i hot an error (the core is locked up) and failed to erase memory. The i unlocked through st link 004 version. Then i flashed with adc variant and it worked. One handlebar made both wheels go backwards and the other made both wheels go different direction. After this i have flashed hovercar and it works but it's a bit of a stuttery ride.

Another thing is with the sideboard. The program pins are in different location but i know + and -. Can i brake the st link if i put swdio and swdclk wrong?

**Comment by Candas1** [comment]
No it shouldn't be a problem.

**Comment by genetgenet** [comment]
I have the same issue as timtimmahh with the sideboard. The pinout is different with + and - on the end sides. I can't unlock the MCU with st link 004, with cube32 it seem to unlock but when i try to flash i get errors. I will post pictures.

**Comment by genetgenet** [comment]
![error flashing sideboard](https://user-images.githubusercontent.com/50130313/118096532-c5066700-b3d1-11eb-8a41-44890d0b643d.jpg)
![Namnlös](https://user-images.githubusercontent.com/50130313/118096534-c59efd80-b3d1-11eb-8c68-4b142b768fb9.jpg)
![Stcube32 error flashing sideboard](https://user-images.githubusercontent.com/50130313/118096537-c59efd80-b3d1-11eb-9c3b-fa60a3b4caf1.jpg)

**Comment by Candas1** [comment]
How are the option bytes looking like in st-utility? Can you take a screenshot?

**Comment by Candas1** [comment]
Check WDG_SW there and try to flash again

**Comment by genetgenet** [comment]
I have not tried to flash again after the comments above just yet. But i will :) 

Test drive :) 

https://youtube.com/shorts/hZqs0wvJkX8?feature=share

**Comment by genetgenet** [comment]
Stutters at start but then it runs fine.

**Comment by EmanuelFeru** [comment]
Did you try to swap motor phases? And do you have freewheel when pedal is 0?

**Comment by genetgenet** [comment]
![WDG_SW checked error 1](https://user-images.githubusercontent.com/50130313/118160358-7fbc5680-b41e-11eb-84dc-3f215989d722.jpg)
![WDG_SW checked error 2](https://user-images.githubusercontent.com/50130313/118160363-80ed8380-b41e-11eb-808a-069db8459a89.jpg)

WDG_SW unchecked is successful but if i check WDG_SW i get the following error as in the pictures.

I have swapped the motor phases by clockwise (so to say) Yellow to Blue, Blue to green, Green to Yellow and so on. The wheels act strange in other phase swap. I have not cross swapped to other variations that don't make sense to me.

**Comment by Candas1** [comment]
Can you use st-link utility software instead?

**Comment by genetgenet** [comment]
![ST link WDG_SW checked error ](https://user-images.githubusercontent.com/50130313/118162901-99ab6880-b421-11eb-9213-b4e810bae467.jpg)

**Comment by genetgenet** [comment]
![ST link WDG_SW checked errorr 
![ST link WDG_SW checked errorr ](https://user-images.githubusercontent.com/50130313/118163237-0e7ea280-b422-11eb-8f6d-034b8a2b8be7.jpg)

Before flash

**Comment by Candas1** [comment]
Can you try to flash now anyway?

**Comment by genetgenet** [comment]
![ST link error before flash ](https://user-images.githubusercontent.com/50130313/118164692-a9c44780-b423-11eb-9f0b-1363a19e7d89.jpg)
![ST link error before flash 2](https://user-images.githubusercontent.com/50130313/118164696-aa5cde00-b423-11eb-840b-525a10f02f11.jpg)

**Comment by genetgenet** [comment]
The file is compiled with vscode and then i chose the firmware bin file in st link program and verify. Is this right ?

**Comment by Candas1** [comment]
You can compile+flash in vscode directly

**Comment by genetgenet** [comment]
![VScode success ](https://user-images.githubusercontent.com/50130313/118166570-eabd5b80-b425-11eb-8c3d-33d2e14ecb48.jpg)

SUCCESS. This is amazing. Thank you so much. I'm glad that this did not work out from the start. I've learned a lot and feel pretty confident of doing this procedure over again :) And thank you EmanuelFeru for all the help.

**Comment by Candas1** [comment]
Yeah it's weird.
You enable an option, you get an error message, but then you can flash 🤔
Had the same with gd32 chip, need to document it.

**Comment by genetgenet** [comment]
Yes it is. Thanks again. 

About the stuttering. The wheel is freewheeling but is making an annoying varience in sound like an irish sack pipe. i wrote before that i have swapped the motor phases by clockwise (so to say) Yellow to Blue, Blue to green, Green to Yellow and so on. The wheels act strange in other phase swap. I have not cross swapped to other variations that don't make sense to me.

**Comment by EmanuelFeru** [comment]
In Torque mode is normal to have some noise, because the current measurement is not perfectly clean and it affects the command.
But the stutter is strange, it should not happen normally. Have you tried other mode, like Voltage to see if it still happens?

**Comment by genetgenet** [comment]
I will test voltage mode. I will have to read up on how to do it.
