### ISSUE TITLE
KZL-BC01-MAIN VER 05 Motherboard with GD32F103 Problem with power button

### ISSUE THREAD

**Issue by Kraxeeer** [EFeru/hoverboard-firmware-hack-FOC#190]
Hello. I've already flashed foc firmware.
Almost stock, just foc and trq mode, also changed 
BOARD_VARIANT           0         // change if board with alternate pin mapping
From 0 to 1
The 1 variant is not working at all
The stock 0 variant is working when i power cpu from programmer (i hear beeps, it's blink led etc) but no power button reaction.
What now can i do with dead mb?
The KZL-BC01-MAIN VER 05 has 5pin halls and two addidionaly red and yellow connectors to, i think, provide 12V and 36V but was not connected in my board. CPU GD32F103
.
I have one dead motherboard with STM32F103 and about replacing stm to gd. i have soldering skills to do that.
![212141907_260290962565516_7470407570442471033_n](https://user-images.githubusercontent.com/10438598/124954606-8dedb400-e016-11eb-96bd-e9ce9fb2cbc8.jpg)
![213016188_329024342026800_2285858473763927505_n](https://user-images.githubusercontent.com/10438598/124954609-8f1ee100-e016-11eb-9fe5-5719b38a2743.jpg)
Sorry for upside down model photo

**Comment by EmanuelFeru** [comment]
If you only Power MCU and you hear beeps than MCU is ok. There might be something with the 2 TIP127 , check if they are not shorted, it always open. And the power latch pin from MCU to TIP127. Because somehow the MCU doesn't get power. So you have to narrow the problem. It can be the TIP127, then the 5V regulator, then the 3.3V regulator.

**Comment by Kraxeeer** [comment]
The motherboard is fine. The problem appeared after flashing. This is my second flashed mb with your fw.

**Comment by Candas1** [comment]
Can this be closed ? It's not a bug.
[Wiki](https://github.com/EFeru/hoverboard-firmware-hack-FOC/wiki/Troubleshooting) has a few more details about what could be wrong on the board.
