### ISSUE TITLE
Is it possible to compile the firmware for GD32F303RCT6

### ISSUE THREAD

**Issue by peerke444** [EFeru/hoverboard-firmware-hack-FOC#191]
Hi,

I've been playing with this firmware for a while with a lot of fun.
So I decided to buy another hoverboard to start a new project.
Unfortunately this motherboard has different processor: GD32F303RCT6.
The brand of the motherboard is TaoTao.
Is it possible to compile the firmware for this processor?

![IMG_3588](https://user-images.githubusercontent.com/46398108/125194874-7b13f300-e253-11eb-9c13-b211fe8dd194.jpeg)
![IMG_3590](https://user-images.githubusercontent.com/46398108/125194877-7e0ee380-e253-11eb-9462-a64d32d5dbc2.jpeg)

**Comment by EmanuelFeru** [comment]
Hi, in not sure if it will work. To bed to do some research. First, to check the MCU datasheet, look at pin, memory and peripherals mapping. Then you have to check the pin mapping to the board, if they match with the firmware. 
I'm sure it's possible to make it work but maybe requires some effort.

**Comment by peerke444** [comment]
Thanks for the tips.
I compared the datasheets and pin mappings.
Except from the fact one has a 108 mhz M3 processor and the other has a 120 mhz M4 processor I can't really find many differences.
Could you give me a hint how to convert your firmware to this processor?
I know my way in arduino but besides that...

**Comment by Candas1** [comment]
Assuming this chip is fully compatible, you also need to check if the pins are mapped in the same [way](https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/wiki/Firmware-Compatibility#pin-mapping)

**Comment by peerke444** [comment]
That is a good question. 
Not really sure how to figure this out...

**Comment by peerke444** [comment]
Ok, I started reverse engineer the PCB.
Most of the mapping I already found.
Some unfortunately not yet.
Below the list of mappings a have so far.
Let's assume I can also find the other mappings.
Could you tell me how to compile your software with the new mappings and for another processor?

This is the list I have so far: 
SWCLK = PA14
SWDIO = PA13
BUZZER = PC15
HALL LEFT U = PB8
HALL LEFT V = PB7
HALL LEFT W = PB6
HALL RIGHT U = PA8
HALL RIGHT V = PA12
HALL RIGHT W = PC10
LEFT UH = PC8
LEFT UL = PB1
LEFT VH = PC7 
LEFT VL = PB0
LEFT WH = PC6
LEFT WL = PA7
RIGHT UH = PA10
RIGHT UL = PB15
RIGHT VH = PA9
RIGHT VL = PB14
RIGHT WH = PA8
RIGHT WL = PB13

**Comment by EmanuelFeru** [comment]
Please have a look at the Driver files for your MCU. Generate a project using MXCube for your MCU, because youmight need completely new HAL_ files.
Would be ideal that the same HAL_files are used for your MCU, the you only need to change the pin definitons in [defines.h](https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/blob/master/Inc/defines.h)

**Comment by peerke444** [comment]
Played some days with CubeMX.
But I think this is a bit to complex for me unfortunately...
Thanks for your help so far!

**Comment by LeonXBB** [comment]
I have made the following table
![image](https://github.com/user-attachments/assets/8bd2a377-475e-48bf-b174-fa8947b50793)
I noticed A8 has two functions. Is it possible or is it a mistake?

**Comment by v-alisei** [comment]
i have hacked it
https://github.com/v-alisei/gd32f303-simplefoc

**Comment by gangstaJS** [comment]
@v-alisei 

Hey. I have the same board, but it's not an F303; it's an F103. It's super confusing. If you look at the chip, it looks very similar to the F303, but when you connect it to an ST-Link and read it, it reports an F103


<img width="768" height="1024" alt="Image" src="https://github.com/user-attachments/assets/de20107d-6ba4-4328-a9c4-bb4dad2f2ff3" />

<img width="768" height="1024" alt="Image" src="https://github.com/user-attachments/assets/b7e13821-cca1-4830-a340-21fa89219711" />

<img width="431" height="212" alt="Image" src="https://github.com/user-attachments/assets/3666c2db-465b-4633-88ad-ab62317ce372" />

**Comment by v-alisei** [comment]
dont trust stlink on this one

**Comment by gangstaJS** [comment]
> dont trust stlink on this one

@v-alisei,  I built and flashed it with F103 firmware; the buzzer on GPIO_PIN_15 is working. Can it be proof that it is F103?

**Comment by v-alisei** [comment]
@gangstaJS 
NO YOU @@@@@ YOU HAVE MARKINGS. stlink determines chip model by fetching some registers, like device id. gigadevice leave it as 414 on most of their chips perhabs for compatibility reasons. some registers are similar between 303 and 103, like gpio port init, but in things like timer, they are completely different. you cannot compile this fw to 303 without modifying spl timer init code. more than that, 303 is cortex m4, while 103 is m3

**Comment by novval** [comment]
> > dont trust stlink on this one
> 
> [@v-alisei](https://github.com/v-alisei), I built and flashed it with F103 firmware; the buzzer on GPIO_PIN_15 is working. Can it be proof that it is F103?

If you fix the pinout in the program, you can compile it for the 103rd processor, and flash it into the 303rd, and it works - tested!
