### ISSUE TITLE
problem with USART GD32F103

### ISSUE THREAD

**Issue by olegi4a** [EFeru/hoverboard-firmware-hack-FOC#197]
I use standard firmware with the following settings:
#define VARIANT_USART // Variant for Serial control via USART3 input
#define CONTROL_SERIAL_USART3
#define FEEDBACK_SERIAL_USART3
// #define DEBUG_SERIAL_USART3 - commented out

the board does not squeak!!! using the site for UART control, all data coming from the board are displayed (speed, battery voltage ...).

PROBLEM - the board does not respond to the joystick from the site, just does not respond to the Arduino with the control firmware.
  on usart2 just the same problem.

I have two more boards on STM32F103 - everything works perfectly !!!

**Comment by EmanuelFeru** [comment]
Can you post a picture with your GD board?

**Comment by olegi4a** [comment]
the board works flawlessly in ADC mode

> Можете ли вы опубликовать картинку с помощью доски GD?


![PXL_20210724_104111138](https://user-images.githubusercontent.com/60703322/126866036-573d2961-015b-485e-976c-96707838bb75.jpg)
![PXL_20210724_104111138](https://user-images.githubusercontent.com/60703322/126866050-9318b981-7603-4645-9f68-00634b60c058.jpg)

**Comment by Candas1** [comment]
Hi,

Can this be closed ?
ADC is on the left wire, you are using USART3 so the right wire. It could be your RX pin on USART3 is defective.
You could try USART2 instead.
https://github.com/EFeru/hoverboard-firmware-hack-FOC/wiki/Variant-USART
