### ISSUE TITLE
Bug on SPD_MODE

### ISSUE THREAD

**Issue by s56jsc** [EFeru/hoverboard-firmware-hack-FOC#199]
After I try to find why SPD_MODE not work as expect I finally got something.
I note that wires at motor become extremely hot if I stop motor by my hand. I_MOT_MAX was set to 2A but on power supply note 20+A before driver cut out. Also if I change I_MOT_MAX to some other value it was the same.  So in this mode current is ignored! 
The same is also I change I_DC_MAX to 10A

I_MOT_MAX work perfect in VLT_MODE

**Comment by EmanuelFeru** [comment]
The current limitation is applied no matter the mode in FOC. I can double check just to be sure.

**Comment by Candas1** [comment]
After Auto-calibration current limits are saved in eeprom, changing it in config.h won't work.
