### ISSUE TITLE
Adc not working

### ISSUE THREAD

**Issue by WilliamAnderssonDev** [EFeru/hoverboard-firmware-hack-FOC#209]
Hello, i can't get adc to work. Iam using 2 potentiometers and i know its not a hardware issue because it works when i use Niklas Fauth's firmware.

Can someone help me with a config file, i really dont need steering i just need to move forward with 1 10k pot

**Comment by EmanuelFeru** [comment]
You have to connect both Potis otherwise you get a timeout. If you only want to use one poti then you have to disable one channel in the firmware. You need to have a look in the code.

**Comment by WilliamAnderssonDev** [comment]
I have connected both but it doesnt work

**Comment by WilliamAnderssonDev** [comment]
I dont think it detects them, they are connected like this 
![connection](https://user-images.githubusercontent.com/62219415/129686620-cd3cc809-e4e7-46ef-b5c1-613a9afc37a4.png)

**Comment by vamfun** [comment]
Might be a calibration issue.      Do a memory erase and repeat the full calibration procedure.

http://vamfun.wordpress.com
Robot musing blog
iPhone

**Comment by WilliamAnderssonDev** [comment]
Hello now the board doesnt turn on at all, not by power and nothing happens when i connect programmer

**Comment by WilliamAnderssonDev** [comment]
It worked, then i power everything off and disconnect battery and went for food and now when i plug everything back in it doesnt work

**Comment by vamfun** [comment]
verify that 3.3 v is present on programming plug…if that’s ok take a look at https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/issues/129

This saved me😎

http://vamfun.wordpress.com
Robot musing blog
iPhone

**Comment by WilliamAnderssonDev** [comment]
No voltage

**Comment by vamfun** [comment]
Make sure you have battery voltage on board input.   Hold the switch in on position and measure 3.3 pin.   If still no 3.3 then possible switch problem or power circuits. Replace switch with jumper and retry 3.3 v measurement.


http://vamfun.wordpress.com
Robot musing blog
iPhone

**Comment by WilliamAnderssonDev** [comment]
I have tested all and still nothing so i will buy a new board

**Comment by Candas1** [comment]
Hi, any updates ? Can this issue be closed ?
