### ISSUE TITLE
High torque & low acceleration at start. How to do?

### ISSUE THREAD

**Issue by kris86k** [EFeru/hoverboard-firmware-hack-FOC#213]
Hi.
- VARIANT: ADC
- CONTROL TYPE: FOC_CTRL
- CONTROL MODE: TRQ_MODE
- What is your application?
    - Lawnmower with sitting driver, three wheels with a steering wheel.

I need low speed max 7km/h and high torque but with low acceleration.
I will change N_MOT_MAX to 50-70. Speed is ok but acceleration is very high. 
I will change DEFAULT_SPEED_COEFFICIENT to 4000-8000 acceleration is ok but strength is very low too, I mean when drive on hard surface is ok but on the grass (or slope or heavier driver) no possible to start, wheels not spin. 
Changed I_MOT_MAX to 30 and I_dc_MAX to 35 but not help.

This is my settings 
[lawnmower.txt](https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/files/7071325/lawnmower.txt)

Thanks for help.
Kris

**Comment by EFeru** [comment]
Hi Kris,

For such low speed have you considered using speed mode SPD_MODE? And in combination with DEFAULT_SPEED_COEFFICIENT maybe you can get a nice smooth tuning.

Also note that depending on the load in SPD_MODE you can get oscillations, so it could be that you need to re-tune slightly the PI speed controller, more precisely these parameters:
https://github.com/EFeru/hoverboard-firmware-hack-FOC/blob/669d2278980b118fed1041d49f2a590c650c5637/Src/BLDC_controller_data.c#L303-L306
https://github.com/EFeru/hoverboard-firmware-hack-FOC/blob/669d2278980b118fed1041d49f2a590c650c5637/Src/BLDC_controller_data.c#L330-L333
