### ISSUE TITLE
Hello, teachers, I come from China, I have a question to ask 

### ISSUE THREAD

**Issue by mouixong** [EFeru/hoverboard-firmware-hack-FOC#215]
I in an accidental opportunity discovered that your this firmware is really too good, is extremely good, specially that 4 gears may shift gears I like it very much, but I found a problem in the process of using it, that is, it will shut down automatically after releasing the throttle, but my voltage is normal, and the battery is just full
But I do not seem to have this problem with other firmware I hope that teachers can give me pointers Teachers, do you use Wechat?You can add my wechat if you can 290970116

**Comment by EmanuelFeru** [comment]
Is there a way to log the battery voltage from serial while the shutdown is happening?

**Comment by mouixong** [comment]
Is there any way？

**Comment by EmanuelFeru** [comment]
Serial communication using FTDI adapter

**Comment by mouixong** [comment]
Is there a tutorial on this? I Don't know much about this， I have a Bluetooth module in my hand

**Comment by EmanuelFeru** [comment]
With Bluetooth module is possible too. Check the wiki pages in this repo.

**Comment by mouixong** [comment]
wiki above the text tutorial is relatively simple, for us this kind of rookie a little do not understand, there is this aspect of video teaching?

**Comment by vamfun** [comment]
As suggested using Debug USART2 or USART3 to FTDI is easiest but it depends on how fast the shut down occurs.   The battery voltage has a low pass filter before debug print..I don’t recall the smoothing lag time constant.   But it can create a delay so you might miss the full transient before shutdown.

The best method is to use an oscilloscope to monitor voltage directly on board.   If no Oscilloscope then  try just a VOM meter but these have lags too..but at least you might see a drop if the transient isn’t too fast,

http://vamfun.wordpress.com
Robot musing blog
iPhone

**Comment by Candas1** [comment]
[Wiki](https://github.com/EFeru/hoverboard-firmware-hack-FOC/wiki/Battery/_edit#troubleshooting) has now more details to troubleshoot such issues.
