### ISSUE TITLE
Support for different hardware (SMART-L-V2.1, two controller boards equipped with STM32F103C8T6)

### ISSUE THREAD

**Issue by andishock** [EFeru/hoverboard-firmware-hack-FOC#218]
Hello folks,
I know this firmware supports only the hardware consisting of the single mainboard controlling both of the hoverboard motors. I just wonder, if anybody around here stumbled over a different kind of hardware consisting of two identical controller boards each equipped with a STM32F103C8T6. There is a printing "SMART-L-V2.1" onto it. The pins for the JTAG/SWD connectors I soldered myself, so don't worry about that.
Does anybody know about some custom firmware supporting this kind of hardware?
Thank you!

![SMART-L-V2 1_small](https://user-images.githubusercontent.com/38784810/132528806-b312e35e-14bf-4f8d-aaf5-7c76c181ccc4.jpg)

**Comment by Candas1** [comment]
Hi,

Have you checked [this](https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/wiki/Firmware-Compatibility)

**Comment by andishock** [comment]
Hi,
Thanks for our answer!
Yes, I already checked for similar boards out there, but none of them seems to be compatible to the hardware I found.

**Comment by Candas1** [comment]
Actually in the meantime I found out the split board firmware is not working on STM32F103C8T6, someone would need to port it.

**Comment by Candas1** [comment]
This new port might be the right place to start:
https://github.com/JohMah/Hoverboard-JC2015.7.31.V2.0-Hack

The board looks different so pin mapping would have to be checked, but at least the chip looks compatible.

**Comment by L1mp4** [comment]
Hi! Did you find anything simple to make this run like you want it? Thanks!

**Comment by zimmii91** [comment]
hi ! i got the same board, in 2 hovers actually. any luck on programming?

**Comment by I-hate-2FA** [comment]
so far no gen2 f103 support on any firmware yet other then the ones modified from gen1, but i am working on porting mine to f103

**Comment by Candas1** [comment]
> This new port might be the right place to start:
> https://github.com/JohMah/Hoverboard-JC2015.7.31.V2.0-Hack
> 
> The board looks different so pin mapping would have to be checked, but at least the chip looks compatible.

Hum hum
