### ISSUE TITLE
VARIANT_HOVERBOARD about balancing controller

### ISSUE THREAD

**Issue by stbnrivas** [EFeru/hoverboard-firmware-hack-FOC#219]
Hi there, I would like to thank you very much the great job. I just buy a hoverboard to play,  I already flashed the mainboard with and also the sideboard (GD32F130C8T6) to use like VARIANT_HOVERBOARD.  The hardware don't make a beep like troubleshooting show, so I suppose that communication between main and sideboard it is working. 

But the hoverboard don't move fordward or backward when I incline or balance. I thought that VARIANT_HOVERBOARD will be usable despite the comment into README: 

> VARIANT_HOVERBOARD: The mainboard reads the two sideboards data. The sideboards need to be flashed with the hacked  version. The balancing controller is not yet implemented.

Is VARIANT_HOVERBOARD usable? or I'm missing something

 thanks so much in advanced.

**Comment by Candas1** [comment]
Hi,

As mentioned in the [main page](https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC#example-variants) and in the [wiki](https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/wiki/Variant-HOVERBOARD), Hoverboard variant is not finished, the balancing hasn't been implemented.
