### ISSUE TITLE
Print out USART feedback

### ISSUE THREAD

**Issue by darld** [EFeru/hoverboard-firmware-hack-FOC#221]
Do we have any exisiting python / c++ file that able to print out all the information from the USART feedback in a single terminal?
Note: I am using RPI UART2 connect to the mainboard. 
 
https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/blob/928a86b86bacf5331405fbbb990b07d82366717a/Arduino/hoverserial/hoverserial.ino#L43-L61

**Comment by Candas1** [comment]
Hi,
Have you checked the wiki?
