### ISSUE TITLE
Turn Mosfets off on start or throttle < 10

### ISSUE THREAD

**Issue by valera3258** [EFeru/hoverboard-firmware-hack-FOC#223]
Hi all, is there any solution to get transistors off when throttle is close to zero or when i turning on device, like on hoveboard to get free wheel in ADC, FOC_CTRL?
As well, when wheel is spinning faster than throttle is pressed, make mosfets turned off or not interfere to wheel control, only listening inputs.
i'm tryed all control modes in FOC_CTRL, and no one of them looks safe for bike with hover motor.
Thanks.

**Comment by Candas1** [comment]
Hi,

Is it not what Torque mode is for ? In this mode 0 command means freewheeling.
Have you tried it ?

**Comment by valera3258** [comment]
Yes im tried, and its not wat i expected for.
The wheel tries to immediately change speed, and this is a problem, in other side, i can't get trottle value smooth like 0-100 (0.8v-2.535v) in this mode.
Im tried to change code, but no results, needs more practice with coding for stm32, im more on c# or java, so therefore i asked.

**Comment by Candas1** [comment]
I don't understand what you mean with your first sentence.

For the non linearity in torque mode, assuming you calibrated well your inputs, it's a known [issue](https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/issues/167) discussed here.

**Comment by valera3258** [comment]
I have bike with 16 inch wheels, and mounted in front wheel 350w motor, if kid riding from hill on 25km and tries to press throttle pedal on 5% wheel starts stopping, converting energy in heating, and im try to fix this in code, sorry if i cant explain correct.

**Comment by Candas1** [comment]
Did you finally get it to work ?

**Comment by Jenya-m** [comment]
Most likely, your halls are not connected correctly ... (I have come across this. The wheel seems to spin smoothly, but it is buggy when braking)
// #define MOTOR_LEFT_ENA
#define MOTOR_RIGHT_ENA
#define CTRL_TYP_SEL FOC_CTRL
#define CTRL_MOD_REQ TRQ_MODE
#define FIELD_WEAK_ENA 0
#define VARIANT_HOVERCAR
#define CTRL_MOD_REQ TRQ_MODE
works for me so great.
