### ISSUE TITLE
feedback data cannot control the Variants usart board?

### ISSUE THREAD

**Issue by ccfxy** [EFeru/hoverboard-firmware-hack-FOC#229]
I see the feedback data was very like the usart control data,but the feedback data cannot control. Is there any way to change the feedback data.
I use dual input,one pwm and usart, usart3 input pwm,usart2 ouput feedback data, the usart2 linked another board to control.but I see the data was not same.
control data:
![ctrl4](https://user-images.githubusercontent.com/92360770/136915225-ca4c6855-8a0a-40a0-9fe7-50c924a2420b.png)
feedback data
![feedback](https://user-images.githubusercontent.com/92360770/136915238-5997b58d-db5e-4724-81f5-8f8110393d57.png)

**Comment by ccfxy** [comment]
> Hi,
> 
> You mean daisy chaining 2 boards ? I thought about that but I never implemented it.
> 
> For the time being the best option is to connect your arduino and receiver to both bo

connect both can be work，just want to find other way，and there was  someone succeed already。i think should change feedbackdata'format

**Comment by longcat99** [comment]
It’s a success, it’s really optional, it will make 4wd better
