### ISSUE TITLE
YST-DXT-J20 Mainboard firmware doesn't drive properly

### ISSUE THREAD

**Issue by scagdas** [EFeru/hoverboard-firmware-hack-FOC#230]
### Your System
- VARIANT: USART
- CONTROL TYPE: FOC
- CONTROL MODE: SPD_MODE

I have new generation cards with bluetooth. Board has YST-DXT-J20 tag on it and  GD32F103RCT6 as main controller. I have successfully flashed the firmware and connected to mainboard with UART however motors doesn't turn with a given speed. Even with low speeds Motor at the mainboard side turns very fast and other one  doesn't turn at all. After going through the previously posted issues I have seen some people managed to fix the issue by swapping phase cables so I have tried all combinations of three cables but it didn't fix the problem for me.

![photo1634112102](https://user-images.githubusercontent.com/40628298/137121841-2e4818ce-f0b1-4352-95b1-7d57c2b948e9.jpeg)

![photo1634112101](https://user-images.githubusercontent.com/40628298/137121850-d0a92eca-4fd2-43c4-b5ae-5fcec85635f9.jpeg)

Any advice how to find and fix the problem?

**Comment by Candas1** [comment]
Have you tried voltage mode instead of speed mode?

**Comment by Candas1** [comment]
Came across this comment:
https://github.com/lucysrausch/hoverboard-firmware-hack/issues/97#issuecomment-896240804

**Comment by villamany** [comment]
Hi, try swapping hall pins definition in "definies.h" file, mine works swapping the V / W hall pins on both motors.

Here is mine: 

#define LEFT_HALL_U_PIN GPIO_PIN_5//GPIO_PIN_5
#define LEFT_HALL_V_PIN GPIO_PIN_7//GPIO_PIN_6
#define LEFT_HALL_W_PIN GPIO_PIN_6//GPIO_PIN_7

#define LEFT_HALL_U_PORT GPIOB
#define LEFT_HALL_V_PORT GPIOB
#define LEFT_HALL_W_PORT GPIOB

#define RIGHT_HALL_U_PIN GPIO_PIN_10//GPIO_PIN_10
#define RIGHT_HALL_V_PIN GPIO_PIN_12//GPIO_PIN_11
#define RIGHT_HALL_W_PIN GPIO_PIN_11//GPIO_PIN_12

**Comment by Candas1** [comment]
Assuming this board is the same as the AT32 board, but only with a GD32 instead, those are the differences that are highlighted and mentioned in the discussion I have shared:
- ADC current reading has to be swapped between phase A and B on the left side in bldc.c
- offsets have to be reset after each enable in bldc.c (I don't know what's the reason behind this change)
- current limiting is not working
- FOC is not working, you should probably try with sinusoidal instead
