### ISSUE TITLE
Stock firmware save..

### ISSUE THREAD

**Issue by mrendu43** [EFeru/hoverboard-firmware-hack-FOC#231]
Hello..
I just found this piece of art and wanna experiment with it, but also i wanna save original firmware when i wanna use hoverboard as hoverboard...
I know it is impossible to read firmware from STM and save it, but i have idea how to do this...
So if anyone have similar problem as i have, this idea might be good for you to...
I planning to order another STM mcu and replace it, and save original one with original firmware if i wanna place it back and us it as hoverboard...
Of course this metod will need some soldering skills and hot air soldering station

**Comment by EFeru** [comment]
As far as I know and heard about the attempts, there is no proper/working backup of factory firmware mainboard and sideboard. Chinese people manged to keep it protected, no leaks yet.
