### ISSUE TITLE
Making variant hovercar "kids safe"

### ISSUE THREAD

**Issue by d3rsch0rsch** [EFeru/hoverboard-firmware-hack-FOC#232]
### Your System
- VARIANT: hovercar
- CONTROL TYPE: foc
- CONTROL MODE: trq
- What is your application?
    - Hovercar **for KIDS**

Hi guys, thanks for this awesome firmware. I managed to get everthing up and running with help of the wiki.
However, i build this as a kids car, and therefor i would like to add two things, which i´m not able with my programming skills.

1. How can i limit the max speed for hovercar variant (i think utilizing the max rpm value would be OK, but i wonder if there is a better solution)
2. Most importantly: How can i limit the reverse speed to a specific value? (or at least a percentage of the max forward speed (see 1.)
3. (optional, not important) Is it possible to bring the "reverse" function away from the brakepedal, and make a small input (button press or something) to switch between forward/reverse. -> So throttle is always the choosen direction, no backwards accelerate through the brake pedal.

Help would be much appreciated, as this is the last issue i have before giving this to my kids withour worries.

Thanks in advance!

**Comment by EFeru** [comment]
Looks awesome! Thanks for sharing! Welcome in the cool daddy club! ;)

**Comment by gba131** [comment]
Hey . Check the fork bbcar from larsmm . It incorporates all the required features with selectable modes and has been tested successfully by (on) kids :)
