### ISSUE TITLE
Nunchuk only works after Flash

### ISSUE THREAD

**Issue by TimoSEL** [EFeru/hoverboard-firmware-hack-FOC#235]
- VARIANT: VARIANT_NUNCHUK
- CONTROL TYPE: Nunchuk

- What is your application?
    - Bollerwagen

Compiling Standard Firmware "VARIANT_NUNCHUK" Using Platformio (in Studio Code)

After flashing, the nunchuk works. But after restart it doesn't work anymore. Tried with calibration and without.
No error beeping unless I disconnect the nunchuk.

Niklas Fauth's firmware is running, but would like to change due to the extensions.

I don't think it's a BUG so I'm just asking what I'm doing wrong.

**Comment by Candas1** [comment]
Hi,

Any updates on this issue ?
