### ISSUE TITLE
compatibility question - Unique mainboard and 7s battery

### ISSUE THREAD

**Issue by j8d** [EFeru/hoverboard-firmware-hack-FOC#237]
### Your System
- VARIANT: ADC
- CONTROL TYPE: FOC
- CONTROL MODE: TRQ
- What is your application?
    - eTrike

Curious if anyone has come across the following board? Trying to determine if a) I'm going to brick it attempting to flash and b) if the board can handle a 10s (or maybe 12s) battery. It has GD32F103RCT6 and the two 220u input capacitors are rated at 50v. 

![20211108_112816](https://user-images.githubusercontent.com/4845675/140792077-558703f1-1c4c-4bda-8609-4c9a994ead73.jpg)

**Comment by Candas1** [comment]
Hi,

It looks very different.
I wouldn't flash it without checking the pins are mapped in the same way:
https://github.com/EFeru/hoverboard-firmware-hack-FOC/wiki/Firmware-Compatibility#pin-mapping

**Comment by j8d** [comment]
Pinout appears to be standard. Going to flash it and hope for the best. 

Also, here's a visual of pinout I put together in case anyone else finds it useful. 

![image](https://user-images.githubusercontent.com/4845675/140996547-5ae0745d-f309-4b53-9f78-e094eb5fbd2a.png)

**Comment by j8d** [comment]
Stuck in bootloop after flash. Power on chime, low tone beep, power off chime. Anything I can do or is it bricked?

**Comment by Candas1** [comment]
Tick all the option bytes in st-link utilityLe 13 nov. 2021 23:06, Ryan ***@***.***> a écrit :
Stuck in bootloop after flash. Power on chime, low tone beep, power off chime. Anything I can do or is it bricked?

**Comment by j8d** [comment]
Thanks! I was able to erase the chip but I'm still getting a bootloop when I flash the firmware. Going to try some other builds.

**Comment by Candas1** [comment]
But have you ticked WDG_SW option?

**Comment by j8d** [comment]
Yes, I got it to stop powering off by reducing BAT_CALIB_ADC. But no motor control via pots, and I'm no longer able to power down the board without disconnecting the battery. Suspect something with my having a 24v battery?

**Comment by Candas1** [comment]
Have you checked this?
https://github.com/EFeru/hoverboard-firmware-hack-FOC/wiki/Battery

**Comment by j8d** [comment]
Thanks Candas. Will work on getting serial debug working

**Comment by Candas1** [comment]
I had overlooked that you were using a 7s battery.
What you describe is not a loop, the firmware is turning of because of the battery voltage being too low for 10s.
Some users really experience a loop, with the firmware turning off/on/off/on, but this is related to the option bytes/watchdog.

The link describes how to setup the right number of battery cells, this will solve your problem.
The calibration is not mandatory but it helps have a more accurate voltage measurement.

**Comment by j8d** [comment]
Thanks. Yes, I already had BAT_CELLS set to 7 and BAT_CALIB_REAL_VOLTAGE set to measured value (2529). Hopefully debug will provide more info. Maybe a hardware issue. Worst case I have a second board I can try flashing

**Comment by j8d** [comment]
Unable to get either board working with the firmware. These appear to be the standard main boards in Swagtron brand 24v hoverboards. Happy to donate these two boards to anyone interested in exploring further.

**Comment by Candas1** [comment]
It's still powering off ? With chime? 
There can be only 2 reasons for the firmware to power off, low battery or inactivity. You can try to disable the power off, would give you time to check the debug output

**Comment by j8d** [comment]
I just finished flashing a standard st32F103 36v mainboard. Worked great before flash. Now, momentary press of the power button does nothing. Holding power button for >2 seconds causes board LED to illuminate until released. But the board won't power on and no serial debug data. Any ideas? The battery is older and will only charge to 36.18v. Could that be the issue?

**Comment by Candas1** [comment]
If there is no power on tune, the chip is either not flashed properly or defective

**Comment by Candas1** [comment]
Hi, I believe you were finally successful, was it with the same board ? this issue can be closed ?

**Comment by SriharshaShesham** [comment]
> ### Your System
> * VARIANT: ADC
> * CONTROL TYPE: FOC
> * CONTROL MODE: TRQ
> * What is your application?
>   
>   * eTrike
> 
> Curious if anyone has come across the following board? Trying to determine if a) I'm going to brick it attempting to flash and b) if the board can handle a 10s (or maybe 12s) battery. It has GD32F103RCT6 and the two 220u input capacitors are rated at 50v.
> 
> ![20211108_112816](https://user-images.githubusercontent.com/4845675/140792077-558703f1-1c4c-4bda-8609-4c9a994ead73.jpg)

Hi,
I have the exact same board. Could someone please provide the pin connection diagram. I keep getting device not found error.

**Comment by WachtelM** [comment]
I know that this thread is very long ago. But I just tried around with the board and while looking carefully at it I noticed that the programming pin is exactly upside down from all the usual boards. If you flip your programming wires it should work
