### ISSUE TITLE
DEFAULT_SPEED_COEFFICIENT min max values

### ISSUE THREAD

**Issue by j8d** [EFeru/hoverboard-firmware-hack-FOC#238]
// Default for SPEED_COEFFICIENT 1.0f [-] higher value == stronger. [0, **65535**] = [-2.0 - 2.0]. In this case 16384 = 1.0 * 2^14

I'm confused here. If 16384 = 1.0 * 2^14, then shouldn't the range be [-32768, 32768]?

If zero is the min value and 65535 is the max value, shouldn't it be:

-2 = 0
-1 = 16384
0 = 32768
1 = 49152
2 = 65536

**Comment by Candas1** [comment]
No it is fixed point
https://github.com/EFeru/FixedPointViewer

Max is 32767 as it's a signed value.
