### ISSUE TITLE
Can we design our own similar circuit so all of us can use based on STM or GD MCU.

### ISSUE THREAD

**Issue by Ability-dis** [EFeru/hoverboard-firmware-hack-FOC#240]
Hi I realized Its very hard to find compatible boards ,Can we make our own PCB design using STM or GD MCU?
In this way all of us can use it and add additional features. We can use it for serving the humanity it will change the life of person with disabilities. There are many things invented but mostly people can't afford specially in the third world. I have seen people dying who can't go for job or even hospital because the can't afford a car or custom made trike . My mission is to make every person with disability can move freely with green energy.

**Comment by Candas1** [comment]
Hi,

I think some community members already designed their own boards
https://github.com/bobbycar-graz/Bobbycar-FOC-hardware
