### ISSUE TITLE
ST-Link serial debug question 

### ISSUE THREAD

**Issue by j8d** [EFeru/hoverboard-firmware-hack-FOC#241]
![ST-LINK-V2-Pinout](https://user-images.githubusercontent.com/4845675/143027847-7ef07d65-b3dd-49e4-abcb-edb3c2878ea9.png)

For serial debug, SWCLK connects to RX and SWDIO to TX?

**Comment by Candas1** [comment]
Hi,

Have you read this
https://github.com/EFeru/hoverboard-firmware-hack-FOC/wiki/Debug-Serial

You can also check the picture in the main page

**Comment by j8d** [comment]
Aha, I misunderstood. The ST-Link V2 is capable of programming only and I need a dedicated uart-usb/FTDI to debug.

**Comment by Candas1** [comment]
Yes exactly, or a bluetooth device like AT-09 or HM-10 if you don't have an ftdi.
