### ISSUE TITLE
 Braking problem with a speed of 0 in speed mode

### ISSUE THREAD

**Issue by ykevin** [EFeru/hoverboard-firmware-hack-FOC#243]
### Your System
- VARIANT:USART
- CONTROL TYPE:FOC
- CONTROL MODE:SPD
- What is your application?
     ROS robot, When the sending speed of the serial port is 0, the motor cannot forcefully lock the brake. When the load is heavy or at a certain speed, the motor will move back and forth once before it stops completely.

**Comment by EFeru** [comment]
Speed mode might require some tuning depending on the load is driving. Meaning you probably need to tune the following PI parameters to have the desired bahavior:
https://github.com/EFeru/hoverboard-firmware-hack-FOC/blob/928a86b86bacf5331405fbbb990b07d82366717a/Src/BLDC_controller_data.c#L303-L306
https://github.com/EFeru/hoverboard-firmware-hack-FOC/blob/928a86b86bacf5331405fbbb990b07d82366717a/Src/BLDC_controller_data.c#L330-L333

**Comment by ykevin** [comment]
thank you
