### ISSUE TITLE
PWM speed channel not working

### ISSUE THREAD

**Issue by villamany** [EFeru/hoverboard-firmware-hack-FOC#244]
Hi everyone. New to this project.
I'm testing the PWM variant but while the steering works, the speed dind't it. Tested the ADC variant and works as expected with the two potis. 
In the PWM variant the "in2" always reads 0 when serial debug. The output train of the RC receiver is ok on both channels.

Thanks

**Comment by Candas1** [comment]
Have you wrongly done the auto calibration maybe?
https://github.com/EFeru/hoverboard-firmware-hack-FOC/wiki/Input-Calibration#auto-calibration

You can check debug output when executing this procedure.

**Comment by villamany** [comment]
yes, but also seems to read always 0.

Input calibration started...
Input1 is a mid-resting pot..OK
Input2 is ignored..OK
Limits Input1: TYP:2 MIN:-999 MID:2 MAX:998
Limits Input2: TYP:0 MIN:0 MID:0 MAX:0
-- Motors enabled --

**Comment by Candas1** [comment]
The firmware works for sure, I have tested pwm myself.
Calibration doesn't seem to detect anything. 
So there could be an issue with your receiver, wiring, or mainboard.

You are saying ADC  works but ADC variant is using left cable, and PWM variant is using right cable by default (shorter). Have you tried pwm on left cable to make sure you don't have a problem on the right cable?

**Comment by villamany** [comment]
Yes, tested on both right and left cable by "#define CONTROL_PWM_LEFT/RIGHT",  same result.
Receiver CHs are ok (tested with oscilloscope), and if i swap the CH1-CH2 wires steering works with CH2 instead CH1, wires also are ok.

I don´t know why the debug shows alway Input2 as TYP:0, although I defined it as type 2

**Comment by Candas1** [comment]
You don't have to change the type.
It will become 0 if you do the auto calibration and  no input is detected.
To be on the safer side erase the chip, flash the firmware, and try without entering the Auto-calibration

**Comment by villamany** [comment]
Same result, full chip erase, redownload the sources, set to PWM mode, and upload. 
Input 2 still reads always 0.

**Comment by villamany** [comment]
![IMG_20211213_205709](https://user-images.githubusercontent.com/5514002/145879713-8b363438-14fb-4adf-b479-126d6787989b.jpg)

![IMG_20211213_205621](https://user-images.githubusercontent.com/5514002/145879738-a56f0ea4-f9a2-483d-a25f-79943467d5af.jpg)

**Comment by Candas1** [comment]
The board looks similar.
When you say that you see a signal for CH2 on the oscilloscope, you see the duty cycle changing when moving the throttle ?

**Comment by villamany** [comment]
> The board looks similar. When you say that you see a signal for CH2 on the oscilloscope, you see the duty cycle changing when moving the throttle ?

Yes

**Comment by Candas1** [comment]
The code hasn't changed for a while, and other community members shared videos of their setup with pwm.
But would be weird that's it's not working on both sides.
Is you receiver only handling PWM ?

**Comment by villamany** [comment]
Tested the PPM variant with a PPM receiver (used the IN2 wire acording to wiki -green wire-), no any signal detected, always shows IN1=0 and IN2=0, so i assume a faulty board in both left/right ports with the same issue!?

**Comment by Candas1** [comment]
Are you sure you use the right number of channels?
https://github.com/EFeru/hoverboard-firmware-hack-FOC/wiki/Variant-PPM

**Comment by villamany** [comment]
In PPM i tried first with16 channels and second select only 4 channels in the Taranis TX configuration. 
Of couse im using Ail and Elev sticks remaped to CH1 and CH2

**Comment by Candas1** [comment]
No beeps ? You should get beeps if the number of channel is incorrect.
Same on left and right ?
What receiver are you using ?

**Comment by villamany** [comment]
I got 4 low beps (no PPM input), i matched the PPM CHs with my PPM RC receiver by  #define PPM_NUM_CHANNELS        8
Checked with oscilloscope my RC PPM train, all seems ok, but still no inputs (the two inputs reads 0)

Here is my PPM signal with the CH1 at minimun (1000ms) and the CH2 at maximun (2000ms), CH3-8 are not used (1500ms)
![pic_32_1](https://user-images.githubusercontent.com/5514002/145963121-3f5ad28a-e85a-402e-ad6c-81d13b6526fe.png)

**Comment by Candas1** [comment]
So even after matching the channels, you get beeps, and from both sides ?

**Comment by villamany** [comment]
yes, tried both sides and both wires on each side.
At power On i got first two low beeps (no ADC) and then start to sound four low beeps forever (no PPM). Of course i got //#define DUAL_INPUTS commemted and using the UART for debug

**Comment by villamany** [comment]
However if i enable DEBUG_SERIAL_USART i should be able to send commands is correct?

I can read data like the calibration result, but if i send a command don't get any reply. IE i send HELP and no any reply

**Comment by Candas1** [comment]
No it's not enough for sending commands, this should be also enabled.
https://github.com/EFeru/hoverboard-firmware-hack-FOC/wiki/Debug-Serial#debug-protocol

**Comment by villamany** [comment]
Sorry, i mean enable  DEBUG_SERIAL_PROTOCOL and no get any reply

**Comment by Candas1** [comment]
Yes then it should work.
It could be both your green wires are not working.

**Comment by villamany** [comment]
is there any way for using as PPM input the blue wire instead the green one?

**Comment by villamany** [comment]
Modified this line in the defines.h files and got PPM train fine in Right side-blue wire.

#define PPM_PIN             GPIO_PIN_10 //GPIO_PIN_11

**Comment by Candas1** [comment]
👍👍👍

**Comment by Candas1** [comment]
Please check USART variant in the wiki.
I saw [this](https://github.com/nabeelfkhan/Toasty) by chance recently

**Comment by villamany** [comment]
Hi, after some tests, R23 and R26 are faulty, some resistance but much more than 100ohm, so its a faulty board. I think probably some time ago in early tests i used the red wire of the port (15v) by mistake instead the 3v3 and fried resistors, with the  pots i get reads but very noisily.

Thanks for all the help!
![pcb](https://user-images.githubusercontent.com/5514002/146574914-a430e5cf-5c60-4ca5-aa36-2c06df18e096.png)
