### ISSUE TITLE
Different hall wiring?

### ISSUE THREAD

**Issue by villamany** [EFeru/hoverboard-firmware-hack-FOC#246]
Hello, my motors some times dont start runing fine, tested all combinations of wiring but the only way i got nice work is swaping hall GPIO V and W in "defines.h file.

#define LEFT_HALL_U_PIN GPIO_PIN_5//GPIO_PIN_5
#define LEFT_HALL_V_PIN GPIO_PIN_7//GPIO_PIN_6
#define LEFT_HALL_W_PIN GPIO_PIN_6//GPIO_PIN_7

#define LEFT_HALL_U_PORT GPIOB
#define LEFT_HALL_V_PORT GPIOB
#define LEFT_HALL_W_PORT GPIOB

#define RIGHT_HALL_U_PIN GPIO_PIN_10//GPIO_PIN_10
#define RIGHT_HALL_V_PIN GPIO_PIN_12//GPIO_PIN_11
#define RIGHT_HALL_W_PIN GPIO_PIN_11//GPIO_PIN_12

**Comment by Candas1** [comment]
Hi,

Yes both phases and halls can be different on some boards.

**Comment by Candas1** [comment]
Do you share a picture of your mainboard?

**Comment by villamany** [comment]
![Uploading IMG_20211219_220219.jpg…]()

**Comment by villamany** [comment]
![IMG_20211219_220219](https://user-images.githubusercontent.com/5514002/146690745-f31fcdca-fa26-4af9-8124-5c9156a2a11d.jpg)

**Comment by Candas1** [comment]
Ok this board doesn't look different.
I am closing this issue as you figured out a workaround already.
Wiki is mentioning about the possibility of swapping phases/hall wires in case of weird behavior.
