### ISSUE TITLE
reverse gear and #define STANDSTILL_HALD_ENABLE does not work?

### ISSUE THREAD

**Issue by perdmen** [EFeru/hoverboard-firmware-hack-FOC#247]
### Your System
- VARIANT: PWM
- CONTROL TYPE: 
- CONTROL MODE:
- What is your application?
    - RC platform
   
In the combination of SIN_CTRL/VLT_MODE, FOC_CTRL/VLT_MODE, VLT_MODE/TRQ_MODE, when you turn on  #define STANDSTILL_HALD_ENABLE, the reverse does not work, is this normal? Is there any way to fix this?

**Comment by EFeru** [comment]
- in SIN_CTRL/VLT_MODE there is no standstill functionality
https://github.com/EFeru/hoverboard-firmware-hack-FOC/blob/669d2278980b118fed1041d49f2a590c650c5637/Src/util.c#L644

- the other should be fixed in last commit, thanks for reporting
