### ISSUE TITLE
ADC voltage reading inaccurate? 

### ISSUE THREAD

**Issue by j8d** [EFeru/hoverboard-firmware-hack-FOC#249]
### Your System
- VARIANT: bbcar fork
- CONTROL TYPE: FOC_CTRL
- CONTROL MODE: TRQ_MODE
- What is your application?
Hover trike

Measured voltage is 53.1v but ADC Voltage reads 6503. Is that expected?
![image](https://user-images.githubusercontent.com/4845675/147587434-cb46833e-825a-4dfc-aa94-c0198eee9c19.png)

Also. Board immediately powers off. Any suggestions? 

https://youtu.be/DWtILUhype8

**Comment by Candas1** [comment]
Please read the wiki

**Comment by j8d** [comment]
I figured it out. #rtfm
