### ISSUE TITLE
Single motor controller

### ISSUE THREAD

**Issue by abrarakram19** [EFeru/hoverboard-firmware-hack-FOC#252]
Hi, i wand to make pcb for single motor controller with F103c8t6 or GD.... MCU, 48pin. Is it possible to flash this firmware on this MCU.

**Comment by Candas1** [comment]
Hi,

Have you checked the differences between f103c8t6 and f103rct6 ?
This firmware is specific to hoverboard mainboards, so it's designed to control 2 wheels, with current sensing for 2 phases + DC, so you would need to adapt it.

This ongoing [project](https://github.com/Koxx3/SmartESC_STM32_v2) is for creating an open source firmware for M365 boards that are for single motor and with STM32f103c8t6 mcu, using STM Motor Control SDK. You should better start there maybe.
