### ISSUE TITLE
Getting the precise position of the motor

### ISSUE THREAD

**Issue by Kandermann** [EFeru/hoverboard-firmware-hack-FOC#257]
Hello, I was wondering if and how I could get the precise motor position using VOLTAGE mode.
I want to use this to connect the board to a pc and use the motor as a direct drive steering wheel.
Would this be possible?
Thanks, Kanderman

**Comment by Candas1** [comment]
Hi,

How to get wheel position was already answered [here](https://github.com/EFeru/hoverboard-firmware-hack-FOC/issues/203).

But as mentioned [here](https://github.com/EFeru/hoverboard-firmware-hack-FOC/wiki/Hoverboard-Wheels) the position cannot be more precise than 4°.

For more precision you need to use an encoder.
There are other people around trying to use hoverboard wheels and this firmware for a direct drive steering wheel. You could  join the telegram group from the link in the main page and reach out to them.
