### ISSUE TITLE
Hi, i flashed my board with this firmware, one motor is spinning in jerky way, i tried to swap motor cables also hall sensor wires but no good results, any advice? 

### ISSUE THREAD

**Issue by Binansh** [EFeru/hoverboard-firmware-hack-FOC#261]
### Your System
- VARIANT:
- CONTROL TYPE:
- CONTROL MODE:
- What is your application?
    - Hovercar, Skateboard, RC platform, etc.

Describe the bug and how we can reproduce it.

```c
// a code sample may improve communication
```

**Comment by Candas1** [comment]
Can you share a picture of your board?

**Comment by Binansh** [comment]
![IMG_20220211_183018](https://user-images.githubusercontent.com/98667016/153620268-fc2cdade-dea8-4884-a685-bc054748bd25.jpg)
![IMG_20220211_183038](https://user-images.githubusercontent.com/98667016/153620278-acd8754f-4212-4805-97b8-7965b2f79716.jpg)
![IMG_20220211_183044](https://user-images.githubusercontent.com/98667016/153620283-fd6f5c68-a8e9-4a2c-8f86-e15eed55f51a.jpg)

**Comment by Candas1** [comment]
The board looks ok.
Only one wheel acts weird?
What if you swap the wheels?

**Comment by Candas1** [comment]
It could be your board is different, maybe a different pin mapping than the one in the wiki:
https://github.com/EFeru/hoverboard-firmware-hack-FOC/wiki/Firmware-Compatibility#pin-mapping
Or the board has a problem.

**Comment by Binansh** [comment]
It was working normal before flashing, i changed hall sensor pins from define.c and nothing good happens, i bought a new board and same of old one and i am hesitant to flash it.

**Comment by Candas1** [comment]
Can you try if it works well in commutation or sinusoïdal mode?

**Comment by Binansh** [comment]
Hello all, i fixed my board it was a hardware problem, it was a SMD capacitor fault in one of the hall sensor circuit i changed it and now it is working in good way.. Thanks for helping.

**Comment by Candas1** [comment]
👍👍👍
