### ISSUE TITLE
Hall effect ebike throttle

### ISSUE THREAD

**Issue by tadkari** [EFeru/hoverboard-firmware-hack-FOC#266]
Im struggleing to connect and map my e bike hall efect throttle. Im a newby in this programming and code metter, so i menaged to turn off steering, but don't know how to change the code for ebike throttle and calibrate it. I know that it cant just be connected insted of a throttle pot, and used with pot and ADC right? So i need help with finding a whey to operate ebike throttle, because im thinking of using this type of controller for my 4x2 wheel mini E QuaD truck and Foc firmware and torque mode is working for me just fine. By the whey, thank you all for development of this wonderfull firmware, it is a great discovery for robotics and EVE enthousiasts.

**Comment by Candas1** [comment]
Hi, have you checked the wiki?

**Comment by tadkari** [comment]
Yes but, didnt find it.

**Comment by tadkari** [comment]
I was looking at calibration section, maby i just need to calibrate the throttle?

**Comment by Candas1** [comment]
Yes calibration will definitely help, you can use the autocalibration.
You will only have a throttle ? No Brake ?

**Comment by tadkari** [comment]
Yes, for now im using only throttle, i have mechanical brakes and a freewheel on my transmisson, so brake wouldn't work anyway.
So i just need to calibrate the throttle? I was hooking throttle to adc set parameters for the pot, like any other noob.

**Comment by tadkari** [comment]
When I set the input_1 of adc to 0, and input_2 to 3- i think 3 is automatic recognition, and hook the throttle, nothing happends, but works again with the pot

**Comment by Candas1** [comment]
But have you done [this](https://github.com/EFeru/hoverboard-firmware-hack-FOC/wiki/Input-Calibration#auto-calibration) ?
Have you read [this](https://github.com/EFeru/hoverboard-firmware-hack-FOC/wiki/Variant-ADC) ?
There is a youtube video, the guy is doing the autocalibration at some point in the video

**Comment by tadkari** [comment]
Done these two things but not working, it doesnt recognise throttle, I put back a pot and it goes fine

**Comment by Candas1** [comment]
Are you sure your throttle is not defective ?

**Comment by tadkari** [comment]
Found a solution, it works with a throttle, i was missing a line in a code wich triggers the auto calibration. Thanks for your time.

**Comment by Candas1** [comment]
but autocalibration is enabled by default, so I guess you have disabled it.

Good that you got it to work

**Comment by tadkari** [comment]
No i did not, i just somehow had a code that was missing that line, it must have been a bug in compiler...

**Comment by tadkari** [comment]
Im now facing with another issue, no metter what amperage i enter in the code for single motor, im stuck with 20Amps max, so how could i possibly overvome this problem? I know that the fets can hendle around 50, I putted thick layer of solder so that it can handle 30Amps easily, so mu question is, should i change the shunts also or just mess with thw code. For now i am using this controller as e bike controller and it saves the battery, and also the motor, but im in a steep hils area so standard 350w ebike controller with 30Amps max is no problem, but this one lowers the amps on steep hils and would not cross 20A.

**Comment by Candas1** [comment]
Yes it's explained why it's happening at the end of this section
https://github.com/EFeru/hoverboard-firmware-hack-FOC/wiki/Setup-current-and-speed-limits

**Comment by tadkari** [comment]
Ive fully erased chip, reprogramed it, and than nothing, i couldn't turn it on anymore.

**Comment by Candas1** [comment]
You probably didn't flash the chip properly.
Are you holding the power button as mentioned [here](https://github.com/EFeru/hoverboard-firmware-hack-FOC/wiki/Compiling-and-flashing-the-firmware) ?

**Comment by tadkari** [comment]
Yes, I did all that, but beeps came after importing other code, but foc wouldnt work several times, and then, after erasing chip and uploading the software finaly got it to work, but amps remain the same, also on steep hills it decreases amps and would come to a stop at 10 amps, full throttle. I set the current of a single motor to 30, and commutation curent to 33, calibrated it and nothing, still up to 20 amps.

**Comment by Candas1** [comment]
My point is after auto-calibration, max current setting is persisted in eeprom, so changing it in config.h and flashing the firmware won't change anything. So you are saying it's still the same after erasing and flashing ?

If you have an ftdi, you could also activate [debug protocol](https://github.com/EFeru/hoverboard-firmware-hack-FOC/wiki/Debug-Serial#debug-protocol), it would let you check and set max current without flashing.

Is there anything else that could limit the current ? What battery are you using ?

**Comment by tadkari** [comment]
40 Amps of constant discharge , and 16Ah 36volt 10s battery im using, i menaged to get the amps higher trough your advices. Calibration helped after second try. Thank you for your time. Im greatfull. I menaged to programe two boards and set the parameters successfully . But third board in TRQ mode works roughly, and im hearing the crunching noise from stator windings, nither of the variants vorks how it should, in TRQ mode there is no free wheeling motor is stuck, works with really low rpm. It is a same chip GD32F103 RCT6. Maby an idea what it could be, it flashes normaly, but when i try it, it is not notmal as two other boards.

**Comment by Candas1** [comment]
Have you tried to swap the phases?

**Comment by tadkari** [comment]
Yes, several combinations, i changed the tip 127 tranzistor because board was turning on on its own when you connect the battery. 
So maby comutation is the problem? Drivers... Or something else?

**Comment by Candas1** [comment]
But it's happening on both wheels?

**Comment by tadkari** [comment]
Yes, on both wheels, and  im testing now only one side, the left one.

**Comment by Candas1** [comment]
How is the board looking like, can you share a picture ?
Is it working well with commutation and sinusoidal control ?

**Comment by tadkari** [comment]
No, its not, first two boards are green, rectangle shaped, and third one is blue.

> 
![IMG-e2fff837cd30c864b0a25e1a8679eb21-V](https://user-images.githubusercontent.com/100387097/156144871-bd0e9132-7917-4f46-b19f-65c3ec598ef7.jpg)
![IMG-5b6837eb9d17de80e33754014ea29096-V](https://user-images.githubusercontent.com/100387097/156144886-718ae77b-98ca-455e-bc89-b5fa79a39ef5.jpg)
 The green one works floles

**Comment by tadkari** [comment]
Its the same chip, programs well.

**Comment by Candas1** [comment]
The board looks ok.
There can be many reasons, you need to check:
- different phase or hall mapping on this board
- defective port on the chip for hall sensor
- defective hall on the wheel
- defective mosfets

**Comment by tadkari** [comment]
Phases are not different mapping, fets are ok, i replaced all 12 fets, wheel works without problems, so afther this mentioned, im left with defective hall port on the chip, i will check that.

**Comment by tadkari** [comment]
Tried everything, but still programes/flashes well, works bad and rough and TRQ mode or any other mode couldnt work properly. So I'm saying its a faulty chip.

**Comment by tadkari** [comment]
How can i change the direction of rotating for one of two motors?

**Comment by Candas1** [comment]
Check hovercar variant in config.h, there are parameters for inverting singke wheel rotation, you can copy it to the variant you use

**Comment by tadkari** [comment]
Oh thank you. You have been very helpful.
By the way i dismissed the blue motherboard because usart left was damaged, and hall sensors reading pins on the chip were gone. So i figured that only full working board can be used with this firmware. I menaged to programe one for my friend, and it works well with the TRQ mode. We are making some kick bikes with two motors so it's wonderful to reuse this controller.
Thank you again, and sory for my bad english, im from Eastern Europe, Balkan, Serbia.
