### ISSUE TITLE
Tachometer/Hall Ticks

### ISSUE THREAD

**Issue by tyler123durden** [EFeru/hoverboard-firmware-hack-FOC#285]
### What can we do to make the firmware better?
In VESC firmware there is a tachometer signal available on the UART interface. AFAIK this is just a wrapping counter of hall sensor ticks which increments at rotations in one direction and decrements in the other direction. So it would be possible to do some basic positioning or limiting tasks.

**Comment by Candas1** [comment]
Hi,

I believe [this](https://github.com/alex-makarov/hoverboard-firmware-hack-FOC/commits/master) fork does that.
