### ISSUE TITLE
4wd rover - PWM input

### ISSUE THREAD

**Issue by JAR4x4** [EFeru/hoverboard-firmware-hack-FOC#292]
Hi, I'm building a rover with an additional aoutopilot. I need to control the four wheels individually as the autopilot will take care of the tank style skid steering.

Is individual PWM control supported by the firmware?

Alex

**Comment by Candas1** [comment]
Hi,

It's available in the last update on my [fork](https://github.com/Candas1/hoverboard-firmware-hack-FOC), I am still testing but will commit soon.
Maybe you can help testing it.
You have to use TANK_STEERING parameter.
Why not using USART instead of PWM ? PWM is really sensitive to noise

**Comment by JAR4x4** [comment]
@Candas1 , thanks for your reply!

I will test your fork in the weekend if i manage to assemble my test platform.

The ardupilot autopilot outputs PWM for each channel. I dont know how I can implement USART...

**Comment by Candas1** [comment]
Is it motor pwm or servo pwm?

**Comment by JAR4x4** [comment]
RC servo / ESC PWM

**Comment by Candas1** [comment]
👍

**Comment by Candas1** [comment]
Hi, it's now also available in this repository
