### ISSUE TITLE
Auto power ON

### ISSUE THREAD

**Issue by landrisan** [EFeru/hoverboard-firmware-hack-FOC#299]
Hello,
Is it possible that de mainboard to autostart on power connect, without the need of power button to be pressed?
I use in an industrial environement, on a complex machine and the need of manualy power on each board is a big problem for me

**Comment by Candas1** [comment]
Hi,

Have you tried something already ?

**Comment by landrisan** [comment]
Hello,
I did, but not a scientific method. I solved the problem for the moment by giving a pulse on power on pin from an external microcontroller. Still need  a better way...

**Comment by landrisan** [comment]
If someone can help me with that... I will be gratefull

**Comment by Candas1** [comment]
A hint from the troubleshooting section of the wiki for a hardware solution:
![image](https://user-images.githubusercontent.com/20670049/167240586-5e84726a-ecb0-4243-a818-6ae2a57b1e50.png)

Another solution would be to replace the button with a jumper, but it requires changes in the code:
- commenting out [this](https://github.com/EFeru/hoverboard-firmware-hack-FOC/blob/4b16b647716ddc7ae03b0674b3b83bf304642c8f/Src/main.c#L209)
- commenting out the call to poweroffPressCheck function
- commenting out the calls to poweroff function might be needed also

**Comment by landrisan** [comment]
Well, works perfectly. No more autopoweroff, works good. Used software soluution, not the TIP127. Was confused anyway, because one of my boards autostarts at power on, with original firmware, while other not. Now I know that was a hardware malfunction... Thank you.

**Comment by Candas1** [comment]
Cool.
You know you don't have to fix this one lol

**Comment by zeezooX** [comment]
> Hello, I did, but not a scientific method. I solved the problem for the moment by giving a pulse on power on pin from an external microcontroller. Still need a better way...

Can you tell me which pin did you send pulses to, the button pin or the latch pin?
