### ISSUE TITLE
Disable standhold

### ISSUE THREAD

**Issue by Protech2021** [EFeru/hoverboard-firmware-hack-FOC#301]
### Variant

ADC

### Description

Can i disable standhold function with button ?
I use this code with button on right cable but it’s not work …

rtP_Left.b_cruiseCtrlEna  = 0;
        rtP_Right.b_cruiseCtrlEna = 0;
        standstillAcv = 0;

**Comment by EFeru** [comment]
You need to make sure it is not re-enabled again by the main functionality in this `if` condition here:
https://github.com/EFeru/hoverboard-firmware-hack-FOC/blob/4b16b647716ddc7ae03b0674b3b83bf304642c8f/Src/util.c#L674

Condition needs to be updated with your button check.

**Comment by Protech2021** [comment]
What you mean by condition need to be update ???

**Comment by Protech2021** [comment]
No body active …
