### ISSUE TITLE
Best eBike settings

### ISSUE THREAD

**Issue by JSphere22** [EFeru/hoverboard-firmware-hack-FOC#307]
### Variant

NUNCHUK

### Control type

FOC

### Control mode

Torque

### Description

Best eBike settings single motor on front: 
//#define MOTOR_LEFT_ENA (Disable left)
#define CTRL_TYP_SEL    FOC_CTRL       
#define CTRL_MOD_REQ    TRQ_MODE        
#define DIAG_ENA        1               

#define I_MOT_MAX       25             
#define I_DC_MAX        27             
#define N_MOT_MAX       1700

#define FIELD_WEAK_ENA  1               
#define FIELD_WEAK_MAX  5              .
#define PHASE_ADV_MAX   45             
#define FIELD_WEAK_HI   1000           .
#define FIELD_WEAK_LO   750 

#define PRI_INPUT1              2, -2048, 0, 2048, 0     
#define PRI_INPUT2              2, -2048, 0, 2048, 0

The only issue is it will start beeping with a single beep with high speed or uphill torque. (Like motor error or a warning )

Also have to disconnect and reconnect Nunchuk on startup.

Anyone have better results?

**Comment by Candas1** [comment]
Hi,

Nunchuk handling was improved in February, are you using latest version of the firmware?

For the motor error, here is a comment Emanuel shared in the telegram group some time ago:

> I'm quite sure you get motor blocked error because of the high load. Increase this threshold to overcome your weight (maybe double the value):
> https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/blob/eb20cc0acad0da91ead7d207fa6a83f1778f03e1/Src/BLDC_controller_data.c#L274
> 
> And you can also increase a bit the debounce time for error qualification:
> https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/blob/eb20cc0acad0da91ead7d207fa6a83f1778f03e1/Src/BLDC_controller_data.c#L197

**Comment by Candas1** [comment]
Any updates ? 
I saw you commented about a throttle stick and ADC variant, but you deleted your message ? you found the issue ?

**Comment by JSphere22** [comment]
Beep issues are gone with additional battery in parallell. Only issue now is stage noise from motor at higher speed. ( like a screeching or whining) But this may be due to the fact that I cut off the entire molded side and replaced with the screw on plate so they are symmetrical.
