### ISSUE TITLE
Electric bike twist throttle 

### ISSUE THREAD

**Issue by Germany111** [EFeru/hoverboard-firmware-hack-FOC#311]
### Description

Who is the best variant to run this throttle it has reverse and 3 speed buttons
![E5D6D353-3A9B-4D30-AF38-D1B4E173F69D](https://user-images.githubusercontent.com/105610135/170000893-cc903dd0-27da-4367-ae32-ef8977e3288e.jpeg)
![A7184F93-692A-4A4C-9355-E96045982ACD](https://user-images.githubusercontent.com/105610135/170000910-50c34a83-e18a-4b99-8f17-48fe0c274337.jpeg)

**Comment by Candas1** [comment]
Hi,

For throttle and brake, you should use the hovercar variant, please read the wiki page that describes how it works. 

The firmware doesn't handle speed/reverse buttons, you would have to adapt the code to your needs.

**Comment by JSphere22** [comment]
![IMG_5252](https://user-images.githubusercontent.com/103326152/170888134-75a389af-cc81-431d-868a-ffe51bc9be8b.JPG)

I can not get this thumb throttle to work. I can not get a single pot to work. I have it wired for speed only and have commented out steering. I have been reading the wiki for months now. Can some help point me in a direction that might help or where to purchase a thumb throttle that works.
