### ISSUE TITLE
4WD simultaneous wheels turn

### ISSUE THREAD

**Issue by MarosMotaj** [EFeru/hoverboard-firmware-hack-FOC#312]
### Variant

USART

### Description

Hi All,

I have 4WD platform with two hoverboards (RC receiver connected via PWM to Arduino UNO. From Arduino UART connection with board1 and board2). Me question is, it is possible to setting up simultaneous wheel turn? Because now when I move with the RC transmitter, one hoverboard is faster. Thanks :)

**Comment by Candas1** [comment]
Hi,

Why don't you use speed control mode?

**Comment by MarosMotaj** [comment]
Hi,

Where can I find it in wiki?

Thanks :)

**Comment by MarosMotaj** [comment]
Can you send me please, how to do that? Thanks :)

**Comment by Candas1** [comment]
> Can you send me please, how to do that? Thanks :)

Please check config.h file

**Comment by MarosMotaj** [comment]
ok, thanks :)

**Comment by MarosMotaj** [comment]
I found it, but how to activate SPD_MODE? I have to comment other mods??

#define COM_CTRL        0               // [-] Commutation Control Type
#define SIN_CTRL        1               // [-] Sinusoidal Control Type
#define FOC_CTRL        2               // [-] Field Oriented Control (FOC) Type

#define OPEN_MODE       0               // [-] OPEN mode
#define VLT_MODE        1               // [-] VOLTAGE mode
#define SPD_MODE        2               // [-] SPEED mode
#define TRQ_MODE        3               // [-] TORQUE mode

**Comment by Candas1** [comment]
> I found it, but how to activate SPD_MODE? I have to comment other mods??
> 
> #define COM_CTRL        0               // [-] Commutation Control Type
> #define SIN_CTRL        1               // [-] Sinusoidal Control Type
> #define FOC_CTRL        2               // [-] Field Oriented Control (FOC) Type
> 
> #define OPEN_MODE       0               // [-] OPEN mode
> #define VLT_MODE        1               // [-] VOLTAGE mode
> #define SPD_MODE        2               // [-] SPEED mode
> #define TRQ_MODE        3               // [-] TORQUE mode

You need to change it here
https://github.com/EFeru/hoverboard-firmware-hack-FOC/blob/4b16b647716ddc7ae03b0674b3b83bf304642c8f/Inc/config.h#L151

**Comment by MarosMotaj** [comment]
Thanks, I set: #define CTRL_MOD_REQ    SPD_MODE
Then I flashed the FW to both boards but the speeds was still diferent...
I configure on ESP32 harware UART ports, first for one board and second to other board and set diferent speed constants regarding on wheel speeds and it is quite good.

**Comment by Candas1** [comment]
👍
