### ISSUE TITLE
Change minimum battery voltage?

### ISSUE THREAD

**Issue by Henrado** [EFeru/hoverboard-firmware-hack-FOC#314]
### Variant

USART

### Control type

FOC

### Control mode

Voltage

### Description

Hello!
I have a 25.5-volt lipo battery (from another hoverboard) that I want to use insted of the originale battery (36 V). Is there a way to change the minimum voltage? Is this possible? Can the main hoverboard board charge the battery properly? 

Thak you in advance :)

**Comment by Candas1** [comment]
Hi,

You haven't checked the [wiki](https://github.com/EFeru/hoverboard-firmware-hack-FOC/wiki/Battery) first.

With a smaller battery, I am not sure ON/OFF button will work for turning the board off.
Of course you cannot use the standard 42v charger with this battery.

**Comment by Henrado** [comment]
Thank you!
