### ISSUE TITLE
How to reduce Amperage without losing speed.

### ISSUE THREAD

**Issue by Misiaa28** [EFeru/hoverboard-firmware-hack-FOC#315]
### Variant

HOVERBOARD

### Control type

FOC

### Control mode

Torque

### Description

Hello I made a skateboard with 4 motors and 2 controllers. how to get max speed decrease acceleration? Currently, setting FIELD_WEAK_MAX to 8 gives higher speed but drastically reduces the range and the engines heat up very much at maximum revs.

**Comment by Candas1** [comment]
Hi,

One way would probably be to increase the voltage, with a 12S battery for example.

**Comment by Candas1** [comment]
Also not all wheels are the same
https://github.com/EFeru/hoverboard-firmware-hack-FOC/wiki/Hoverboard-Wheels
