### ISSUE TITLE
 Board hoverboard with Gd32F103 RC problem firmware variant Nunchuck

### ISSUE THREAD

**Issue by DanGeffry** [EFeru/hoverboard-firmware-hack-FOC#320]
### Variant

NUNCHUK

### Control type

FOC

### Control mode

Torque

### Description

I am currently using the online compiler https://pionierland.de/hoverhack/indexOld.php
But the generated hexadecimal file doesn't work with the nunchuck yet it's the original one. I do not know why? I managed to flash the firmware and there is the beep. But when I wire everything up nothing happens. I just uncommented #define VARIANT_NUNCHUK
But nothing. Can someone help me by emailing me the Nunchuck variant and the USART variant? both binary files please?

I am currently working on a wheelchair for my sister whom I would really like to help with her travels.

Thank you

**Comment by Candas1** [comment]
Hi,

Have you already checked the wiki ?
There we share different ways how to compile the code, there is another method how to compile without installing the software documented.

There are also tips what to check if it's not working.

**Comment by DanGeffry** [comment]
I have errors with platformio.
The only two methods I have tested are this one, platformio and the online compiler. With platformio I can't compile. But with the online compiler I manage to compile but none of the variants work on the hoverboard. On the other hand I got a hexadecimal file for the ADC variant, and this one works well on my hoverboard So I'm lost

**Comment by DanGeffry** [comment]
With Keil the flash works but I don't have a beep. And there is no reaction from my engines.

**Comment by Candas1** [comment]
So you haven't tried [this](https://github.com/EFeru/hoverboard-firmware-hack-FOC/wiki/Compiling-and-flashing-the-firmware#method-0-using-github-fork)

No reaction from the engines doesn't mean the firmware doesn't work, you should check the calibration topic in the wiki

**Comment by DanGeffry** [comment]
I will try to follow your instruction on calibration and I will try again thank you for being available for me. It is true that it is good for me that I manage to do it. So that soon I won't come back for the same thing.

**Comment by DanGeffry** [comment]
ça marche merci beaucoup, merci beaucoup

**Comment by DanGeffry** [comment]
Do you think I can modify to get an even stronger torque? If so where can I modify the code?
