### ISSUE TITLE
PPM input not working?

### ISSUE THREAD

**Issue by rokars** [EFeru/hoverboard-firmware-hack-FOC#327]
### Variant

PPM

### Control type

FOC

### Control mode

Torque

### Description

Hi, Is PPM and PPM sum different, got a flipsky vx1 remote connected to the right side green wire, usart debugging output to my pc through esp32 and can see that in1 and in2 do not move from 0. can see the ppm signal length change on oscilloscope but only looks like 1 channels coming from receiver, also tried other right side pin and left side pins. if i switch to pwm the same ppm receiver works somewhat.

**Comment by Candas1** [comment]
Hi,

How PPM works with this firmware is described in the wiki, there is a parameter for number of channels.
It wouldn't work with a single channel though, and I don't see the point of PPM with a single channel.

If it's meant for a skateboard and PWM works, why aren't you using the skateboard variant ?
