### ISSUE TITLE
use of Hall sensor built in the wheel itself

### ISSUE THREAD

**Issue by 4W4I5** [EFeru/hoverboard-firmware-hack-FOC#330]
### Variant

USART

### Control type

FOC

### Control mode

Torque

### What can we do to make the firmware better?

So i just went through the code and couldnt find code that might easily send hall sensor data to serial, i think itll be really nice since you could get distance travelled with a counter loop implemented in the arduino code if so desired or on the sideboard display

### Describe suggestions or alternatives you have considered

first time making an issue idk what to write here but basically for my project i believe it might be better to have wheel angle in degress (X.XX) sent to the arduino as that is what im using to process the signals and control a motor. For this i just need to know the wheel position and move on from there. i could just do it with wires spliced out from the hall sensor cable but itll be much better to just not mess with that as the motors might be sensitve to emv from extra wires. no need to reinvent the wheel ikr

**Comment by Candas1** [comment]
https://github.com/EFeru/hoverboard-firmware-hack-FOC/issues/285
