### ISSUE TITLE
is it possible to drive the motors with a pwm and a dir line

### ISSUE THREAD

**Issue by SynthetikzZ** [EFeru/hoverboard-firmware-hack-FOC#331]
### Control type

FOC

### Control mode

Torque

### Description

is it possible to provide the controller with a pwm signal for motor strength and a direction signal (0,1)  from another stm board to control the motor?

**Comment by Candas1** [comment]
Hi,

No, the firmware doesn't support this.

**Comment by SynthetikzZ** [comment]
oh i read trough the source code right now, i think i can use the Variant steering with some adjustments

**Comment by Reponja** [comment]
Did you get it to work? I need that functionality for my Force Feedback Simracing wheel i am making out of hoverboard

**Comment by korvolle** [comment]
> Did you get it to work? I need that functionality for my Force Feedback Simracing wheel i am making out of hoverboard

Did you managed to make it work?

**Comment by Reponja** [comment]
> > Did you get it to work? I need that functionality for my Force Feedback Simracing wheel i am making out of hoverboard
> 
> Did you managed to make it work?

Nah, i got myself an Odrive
