### ISSUE TITLE
Board keeps turning off shortly after power on.

### ISSUE THREAD

**Issue by DannySchroeder** [EFeru/hoverboard-firmware-hack-FOC#343]
### Variant

ADC

### Control mode

Speed

### Description

I am attempting to use this firmware to create a rover. I ordered a mainboard online and got it flashed with no issues. However, when I hook the board up to the motors of the hoverboard I'm using, the board will turn off about 5 seconds after I turn it on. I have tried ADC, PWM, and USART modes. I have also tried switching around the hall sensors and motor wires. I think the motors are incompatible because they are not listed on the page of compatible motors. Is this what would happen with incompatible motors? Or could there be a different problem that I am missing?

**Comment by Candas1** [comment]
Hi,

You checked [this](https://github.com/EFeru/hoverboard-firmware-hack-FOC/wiki/Troubleshooting) page ?
