### ISSUE TITLE
The wheels rotate at different speeds.

### ISSUE THREAD

**Issue by vaavdeev** [EFeru/hoverboard-firmware-hack-FOC#347]
### Variant

USART

### Control type

FOC

### Control mode

Speed

### Description

The wheels rotate at different speeds.

UART control via arduino

Motion testing.

steer = 0
speed=200

The scheme is working.
There is a problem.

The monitor shows a slight difference in wheel rotation.
For example, the left wheel is - 199, the right wheel is +106

A slight difference in rotation is visually visible.

Is it possible to make wheel rotation correction in configuration files?

Thank you.

**Comment by Candas1** [comment]
Hi,

199 and 206 you mean ?
Are you sure Steering is zero ?
Have you done auto calibration by mistake ? It's not needed for USART, you can erase the chip in ST-LINK Utility before flashing to be on the safer side

What's your use case ?
I don't speed will always be perfectly 200 anyway
