### ISSUE TITLE
PCB maximum battery voltage

### ISSUE THREAD

**Issue by Japla74** [EFeru/hoverboard-firmware-hack-FOC#348]
### Variant

ADC

### Control type

FOC

### Control mode

Torque

### Description

Hi, I happen to have two NMC battery packs, both max 29,2V. I wonder, that will PCB survive if I connect them in series to supply max 58,4V to the howerboard PCB? I checked that main caps are 63V and fets up to 100V, but is there some unknown limiting factors?

I am creating quad version with rubber tracks, aiming for quite high peak output power.
![image](https://user-images.githubusercontent.com/116088222/196444253-f6f5f7cc-5928-404a-8dc9-82a7f2fd1a28.png)

**Comment by Candas1** [comment]
Hi,

I think it's too close, you would need to upgrade to 100v caps probably.

**Comment by emo8899** [comment]
> If caps is only issue, those I can replace easily. What about internal voltages, smaller ones are done with 7805 etc, but is there any else which would raise too high? Thanks!

hi  Japla
  Have you solved this problem? Can we use a higher voltage?

**Comment by Candas1** [comment]
Check the wiki
