### ISSUE TITLE
Pwm. Control with only one channel

### ISSUE THREAD

**Issue by moonkagliwicee** [EFeru/hoverboard-firmware-hack-FOC#349]
### Variant

PWM

### Control mode

Torque

### What can we do to make the firmware better?

Is it possible to control with only one channel?  I want to use a PWM variant to power a mini car.  I am only interested in using channel 2, i.e. SPEED.  Is channel 1 uncomment enough?

### Describe suggestions or alternatives you have considered

No ideas

**Comment by Candas1** [comment]
Hi,

Have you read the wiki ?

**Comment by moonkagliwicee** [comment]
Yes, but I don't understand everything there
