### ISSUE TITLE
GD32F303RCT6 firmware hack hoverboard.ino don't work

### ISSUE THREAD

**Issue by AnOrdinaryUsser** [EFeru/hoverboard-firmware-hack-FOC#357]
### Variant

USART

### Control type

Commutation

### Description

Good morning to you all,

I am trying to use, a GD32F303RCT6 processor with a tao tao board. This:

![WhatsApp Image 2022-11-21 at 08 55 55](https://user-images.githubusercontent.com/61872281/203006630-1531374f-aede-4357-8b04-2c5335bd7516.jpeg)
![WhatsApp Image 2022-11-21 at 08 55 55 (1)](https://user-images.githubusercontent.com/61872281/203006636-bf669d4c-9122-46cd-bd48-10835818e941.jpeg)

I unlock the motherboard and upload the firmware but But I am not able to use the hoverboard.ino arduino skecth to test the wheels. My problem is that I don't know if I'm misusing the RX and TX pins on the board or if I need to modify something to make it work properly.

**Comment by Candas1** [comment]
Hi,

Have you checked the troubleshooting hints in the wiki ?
I think someone had reported about a board with a F303 chip in the telegram channel, it seemed to work

**Comment by Candas1** [comment]
https://github.com/EFeru/hoverboard-firmware-hack-FOC/issues/191

**Comment by AnOrdinaryUsser** [comment]
> Hi,
> 
> Have you checked the troubleshooting hints in the wiki ? I think someone had reported about a board with a F303 chip in the telegram channel, it seemed to work [edit] Actually there is no proof this board would work, pinout probably has to be checked, and also if there major differences between F103 and F303

What is the telegram channel to see those messages?

**Comment by Candas1** [comment]
Check the links at the end of the main page of the repository.

________________________________
De : AnOrdinaryUsser ***@***.***>
Envoyé : lundi 21 novembre 2022 10:50
À : EFeru/hoverboard-firmware-hack-FOC ***@***.***>
Cc : Candas1 ***@***.***>; Comment ***@***.***>
Objet : Re: [EFeru/hoverboard-firmware-hack-FOC] GD32F303RCT6 firmware hack hoverboard.ino don't work (Issue #357)


Hi,

Have you checked the troubleshooting hints in the wiki ? I think someone had reported about a board with a F303 chip in the telegram channel, it seemed to work [edit] Actually there is no proof this board would work, pinout probably has to be checked, and also if there major differences between F103 and F303

What is the telegram channel to see those messages?

**Comment by Candas1** [comment]
So basically F303 is not supported and it is a lot of work to rewrite the firmware for this chip family

**Comment by v-alisei** [comment]
https://github.com/v-alisei/gd32f303-simplefoc
i have hacked this board
