### ISSUE TITLE
Video. 1. Right wheel won't stop. 2. Bugg when turning wheels.

### ISSUE THREAD

**Issue by DmitrySurgut** [EFeru/hoverboard-firmware-hack-FOC#360]
### Variant

HOVERCAR

### Control type

FOC

### Control mode

Torque

### What is the bug and how to reproduce it ?

Video. Right wheel won't stop. Bugg when turning wheels. https://drive.google.com/drive/folders/1LTxlPl3RY7YzgZsmhaCjnE4IPPUD_CdC?usp=share_link

**Comment by Candas1** [comment]
Both won't happen with load

**Comment by Candas1** [comment]
And if it oscillates you probably have the brake pressed

**Comment by Candas1** [comment]
https://github.com/EFeru/hoverboard-firmware-hack-FOC/wiki/Variant-HOVERCAR#toolbox-troubleshooting

**Comment by DmitrySurgut** [comment]
Why the right wheel does not stop and consumes a current of 1.5A ?

**Comment by Candas1** [comment]
Maybe your board has a problem

**Comment by DmitrySurgut** [comment]
Maybe, thanks, I'll try on another board

**Comment by Candas1** [comment]
Maybe try swapping the wheels to see if the problem is still on the same side

**Comment by DmitrySurgut** [comment]
Swapped the wheels, the problem moved from the left wheel to the right wheel. Video - from the left wheel to the right wheel. https://drive.google.com/drive/folders/1LTxlPl3RY7YzgZsmhaCjnE4IPPUD_CdC?usp=share_link

**Comment by Candas1** [comment]
As I said this is normal with torque mode without load
But it could be the wheel that stops has more friction

Can you try enabling ELECTRIC_BRAKE_ENABLE and make ELECTRIC_BRAKE_MAX very small? Start with 1 maybe and increase until it's not happening anymore. 
If this works we could maybe make this the default

**Comment by DmitrySurgut** [comment]
I lower the accelerator to zero and both wheels should stop, but one wheel still has 2A current and that wheel keeps spinning

**Comment by Candas1** [comment]
You are not reading my replies
Bye
