### ISSUE TITLE
Firmware preset to ADC variant  

### ISSUE THREAD

**Issue by leonmurray** [EFeru/hoverboard-firmware-hack-FOC#361]
### Variant

SKATEBOARD

### Control type

FOC

### Control mode

Torque

### What is the bug and how to reproduce it ?

I can choosd the variant SKATEBOARD in Plaformio, and in config_h, but when I try to build it, it crashes everytime and fails. If I read the "make" script, it constantly says D=Variant_ADC????
I even opened a new GIthub account to Fork it from EFeru/ again, but it doesnt work. It was fine 2 weeks ago but now its broken.????? Any help ? Thanks, Leon

**Comment by Candas1** [comment]
![Screenshot_20221224_214514_com android chrome](https://user-images.githubusercontent.com/20670049/209450630-9d8dab69-58e9-407d-ba5b-5da468c09076.jpg)

When your first change worked, then you changed other stuff randomly
