### ISSUE TITLE
Separate motor speed control & position approximation

### ISSUE THREAD

**Issue by skywa04885** [EFeru/hoverboard-firmware-hack-FOC#371]
### Variant

HOVERBOARD

### Control type

Sinusoidale

### Control mode

Speed

### Description

I want to control both motors separately and change their speeds / read back their position data (sort-off approximated by the HAL sensors in the wheels), before analyzing the entire project, I would like to know if this is possible. In this case I want to control both wheels separately using an Arduino, and check their position (approximation by HAL sensor). Is this possible? Steering won't do the thing, I need full, separate control.

**Comment by Candas1** [comment]
Hi, read the wiki

**Comment by Candas1** [comment]
Look up tank steering

**Comment by skywa04885** [comment]
> Look up tank steering

Okay yes, I've found that. But how can I get the HAL sensor feedback?

**Comment by Candas1** [comment]
It not available with this firmware unless you can code
There is a fork doing that it's linked in the wiki
