### ISSUE TITLE
problem gd32f103

### ISSUE THREAD

**Issue by chachinoi33** [EFeru/hoverboard-firmware-hack-FOC#393]
### Variant

IBUS

### Control type

FOC

### Control mode

None

### Description

hello, I have already done a project in ibus flysky with an stm32f103rct6 card and it worked very well, I now have a gd32f103ct6 card and I encounter this problem. https://youtu.be/rMqWm0DB0JI
Do you know what the problem is?
THANKS

**Comment by Candas1** [comment]
https://github.com/EFeru/hoverboard-firmware-hack-FOC/wiki/Firmware-Compatibility#toolbox-troubleshooting

**Comment by chachinoi33** [comment]
Thank you, I just changed the direction of the right motor phases and it is now turning, but they are still idling

**Comment by chachinoi33** [comment]
I switched to pwm, everything works but I have the left motor which has no more torque (I can stop it by hand)
I tried in torque but it's not better, do you have any idea?

**Comment by Candas1** [comment]
Ibus shouldn't be the problem, it's better than pwm.
It's still a hall problem.

**Comment by chachinoi33** [comment]
thank you very much for the support!  I will try tomorrow to move the hall sensors

**Comment by chachinoi33** [comment]
hello, sorry I did not give news.  I managed to get everything working by inverting 2 hall sensors, but ended up ditching the hoverboard motherboard for ebike controllers.  https://youtu.be/wSHKioaHZvM

**Comment by Candas1** [comment]
👍
