### ISSUE TITLE
Is the firmware compatible with the GD32F303

### ISSUE THREAD

**Issue by tamano123** [EFeru/hoverboard-firmware-hack-FOC#396]
### Variant

USART

### Control type

FOC

### Control mode

Speed

### Description

Hello, i want to buy a motherboard and i found one (chinese) that has the GD32F303 micro-controller. I want to know if this micro-controller is compatible with the firmware ?

In the GigaDevice website (https://www.gigadevice.com/product/mcu/arm-cortex-m4/gd32f303cet6), they said that :

`To help customers make the most of the product's advantages flexibly, the GD32F3x0 series is compatible with the full range of hardware and software of the GD32F1x0 series and GD32E230 series.`

Thank you for your help.

**Comment by Candas1** [comment]
Hi,

Check the wiki and use the search button to find similar questions.

**Comment by tamano123** [comment]
Thank you @Candas1 for your answer but i didn't find a solution (or may be i am searching in the wrong place :-)) in the wiki (https://github.com/EFeru/hoverboard-firmware-hack-FOC/wiki/Firmware-Compatibility) about the compatibility of the GD32F303 microcontoller. I also made a search in the issues (already closed and open) but didn't find any result... please advice me

**Comment by Candas1** [comment]
So you are not able to use the search
https://github.com/EFeru/hoverboard-firmware-hack-FOC/issues?q=F303

**Comment by tamano123** [comment]
So sorry. Thank you -:)
