### ISSUE TITLE
3 beep error after powering on

### ISSUE THREAD

**Issue by Dominykasssx** [EFeru/hoverboard-firmware-hack-FOC#457]
### Variant

USART

### Control type

FOC

### Control mode

Voltage

### Description

Hello there! 

I'm trying to run this firmware first time in my life and I have encouded some problems. I want to control wheels using arduino skech.

I already upload a firmware to the hoverboard mainboard,

Here is the settings:

![image](https://github.com/EFeru/hoverboard-firmware-hack-FOC/assets/50581706/d960c0f7-194c-48c5-a19f-2b402f2e7a13)

![image](https://github.com/EFeru/hoverboard-firmware-hack-FOC/assets/50581706/763ea748-cf2c-4a40-acca-90f72ec603fa)
![image](https://github.com/EFeru/hoverboard-firmware-hack-FOC/assets/50581706/088190f0-66e5-4283-af0a-5b0218859ae1)

Info from debug port:

![image](https://github.com/EFeru/hoverboard-firmware-hack-FOC/assets/50581706/742e4da9-8107-4c73-a42b-a6098b0ee129)

My mainboard continiously beeps. I think it's a 3 beep code and then small pause.

After uploading skech to the arduino, wheels are not moving. Also tested firmware provided here: https://github.com/lucysrausch/hoverboard-firmware-hack/issues/51#issuecomment-418292550

It still beeps, but wheels are spinning themself, so it means it's not a hardware issue. 

I'm using arduino uno which has which has RX pin 0 and TX pin 1. In provided arduino skech there is defined 2,3 RX,TX pins, so I tried using predefined ones pin at first, later changed to 0,1, but it didn't change a thing. 

![image](https://github.com/EFeru/hoverboard-firmware-hack-FOC/assets/50581706/37a9214b-7559-42f7-8efe-a12612224a1c)

Before compiling and uploading arduino sketch I only uncommented this:

![image](https://github.com/EFeru/hoverboard-firmware-hack-FOC/assets/50581706/83a4be83-cf8a-4ebd-92d1-116ac547b756)

Here is the video/sound of the beep: 

https://github.com/EFeru/hoverboard-firmware-hack-FOC/assets/50581706/b18541aa-d3cd-4bda-b3d2-a0e62ec7934d

What could be wrong? Could not see any solutions for this problem online. Thank you for helping :)

**Comment by Amitkor12** [comment]
As per the code the 3 beeps indicates serial timeout duration. try changing this parameter, as per your requirement and check.

**Comment by Dominykasssx** [comment]
> l timeout duration

I have wired serial TTL adapter to arduino pins to see if something is being sent. Indeed, arduino sends some data, but not sure if hoverboard mainboard receives it, how can I test this?

**Comment by Candas1** [comment]
Anyone reading the wiki?

**Comment by Amitkor12** [comment]
> Anyone reading the wiki? 

I have gone through the wiki part and also the code of arduino sketch. But not able to find the exact problem 😕

**Comment by Candas1** [comment]
[This](https://github.com/EFeru/hoverboard-firmware-hack-FOC/wiki/Variant-USART#toolbox-troubleshooting)?

**Comment by Dominykasssx** [comment]
Okay, so I have found the problem. I initially selected USART, expecting it to work with USART3 input by default, but it didn't.

Upon reviewing the config.h file, I discovered that USART2 was set as the default (as I understand). 

![image](https://github.com/EFeru/hoverboard-firmware-hack-FOC/assets/50581706/886de73b-2895-4986-9970-2ec9f944753f)

I commented USART2 and uncommented USART3 instead, and now it works fine!

Hope it will help someone.

**Comment by Dominykasssx** [comment]
Closing issue, because it's a simple configuration problem

**Comment by javiersanzsanchez** [comment]
@Dominykasssx I hace the same issue, I also uncomment the USART3 but I still having those 3 beeps connecting the Arduino to the left side (long wire). Can you provide any summary about you connections and cone?

**Comment by carloszambri-lgtm** [comment]
Mi placa emite los tres pitidos pero tengo el gd32 y creo que es por eso estoy cambiando el Bugs en platformio y mañana lo pruebo no tengo ningún voltaje en usart3  a lo mejor debería cambiar mi Arduino nano por otro que pueda utilizar usart2 ya direis
