### ISSUE TITLE
Did not find the SVPWM module in FOC control

### ISSUE THREAD

**Issue by gbgms** [EFeru/hoverboard-firmware-hack-FOC#491]
### Variant

USART

### Control type

FOC

### Control mode

Speed

### Description

SVPWM is an important part of FOC, but I did not see this module in the Simulink model of FOC control, and I did not see it in the code either. In addition, according to my understanding after reading the code, is SPWM used? This problem has troubled me for a long time, I hope to get help, thank you.

**Comment by gbgms** [comment]
> 它用于 https://github.com/EFeru/bldc-motor-control-FOC

Thank you for your response! I’ve already downloaded this Simulink file, but I didn’t find the SVPWM module。According to my understanding of FOC ， after transforming Vd and Vq to Valpha and Vbeta using the Park inverse transformation, they should be modulated using SVPWM. However, in this file, Valpha and Vbeta are directly transformed into three-phase voltage outputs。

**Comment by Candas1** [comment]
https://eferu.github.io/bldc-motor-control-FOC/#slwebview:53

**Comment by Candas1** [comment]
https://developerhelp.microchip.com/xwiki/bin/view/applications/motors/control-algorithms/zsm/zsm/best-zsm/

**Comment by gbgms** [comment]
> https://developerhelp.microchip.com/xwiki/bin/view/applications/motors/control-algorithms/zsm/zsm/best-zsm/

Thank you very much!
