### ISSUE TITLE
change the Board response Time

### ISSUE THREAD

**Issue by samerjawadi** [EFeru/hoverboard-firmware-hack-FOC#503]
### Variant

USART

### Control type

FOC

### Control mode

Speed

### Description

Hello everyone,

I have a question about changing the response time of the board. When I send the target speed via UART, it instantly execute it and tries to reach that speed. 
However, I want it to take some time to reach the target speed (progressively) (linear curve,). Is there any parameter or modification I can make in the firmware to achieve this?

Thank you in advance.

**Comment by Candas1** [comment]
Hi,

Check rate limiting or filtering on the wiki.

**Comment by samerjawadi** [comment]
Hello,

Yup that's what i am looking for.

Thank you for your help.
